# -*- coding: utf-8 -*-
# FaRu Fact - "Facts That Sound Fake" - 14 Shorts. Every claim below was checked
# against the sources listed with it; phrasing follows what the source supports.

V = "vertical 9:16, photorealistic, cinematic, high detail, shallow depth of field, no text, no watermark"

SHORTS = [
dict(day=1, n=1, cat="Prehistoric / animal", hooktype="Comparison ('older than')",
 topic="Horseshoe crabs are older than trees",
 claim="Horseshoe crab fossils date to about 445 million years ago; the earliest known trees and forests date to about 385 million years ago.",
 sources=[("Rudkin et al. 2008, Palaeontology (Lunataspis aurora, 445 Mya)","https://onlinelibrary.wiley.com/doi/10.1111/j.1475-4983.2007.00746.x"),
          ("ScienceDaily: oldest horseshoe crab fossil","https://www.sciencedaily.com/releases/2008/02/080207135801.htm"),
          ("Stein et al. 2007, Nature (Gilboa, earliest forest, ~385 Mya)","https://www.nature.com/articles/nature05705")],
 frame="A horseshoe crab on wet black sand, shot from its eye level, so it fills the lower half of the frame. Behind it, soft-focus: a bare, leafless landscape with no trees. Big text top-third: OLDER THAN TREES.",
 hook="This animal is older than trees.",
 script=[("0.0-1.0","This animal is older than trees."),
         ("1.0-5.0","Not one tree. Trees, as a thing that exists."),
         ("5.0-15.0","Horseshoe crab fossils go back 445 million years. The first forests showed up about 385 million years ago."),
         ("15.0-20.0","Sixty million years of crabs on a planet with no trees. And they're still on our beaches.")],
 osd=[("0.0-1.0","OLDER THAN TREES"),("1.0-5.0","not a tree - ALL trees"),("5.0-10.0","crabs: 445 million yrs"),
      ("10.0-15.0","first forests: 385 million yrs"),("15.0-20.0","60 million years\nwith no trees")],
 shots=[dict(t="0-1s", subj="Horseshoe crab", comp="Low, eye-level, crab in lower half", move="Slow push-in", light="Overcast, cool, wet sheen", trans="Hard cut",
             prompt="a horseshoe crab on wet black volcanic sand, eye-level macro, empty barren landscape behind with no trees or plants, overcast cool light, wet shell glistening, "+V),
        dict(t="1-5s", subj="Barren Ordovician coast", comp="Wide, horizon low", move="Slow pan right", light="Pale dawn", trans="Crossfade 0.3s",
             prompt="a barren rocky prehistoric coastline 445 million years ago, no plants on land at all, shallow sea, horseshoe crabs at the water's edge, pale dawn light, "+V),
        dict(t="5-15s", subj="Fossil in stone", comp="Top-down, fossil centered", move="Rack focus onto fossil", light="Museum spotlight", trans="Whip cut",
             prompt="a fossilized horseshoe crab imprint in grey limestone, top-down, museum spotlight raking from the side to show texture, "+V),
        dict(t="15-20s", subj="Modern beach, crab in surf", comp="Crab in foreground, waves behind", move="Tracking alongside", light="Golden hour", trans="Cut back to shot 1 framing",
             prompt="a living horseshoe crab crawling through shallow surf on a modern beach at golden hour, low angle, waves behind, "+V)],
 sound="Low sub-bass drone (ancient, slow). Hit on 'older than trees' (0.9s). Soft rising swell into the numbers; a clean tick on '445' and again on '385'. Surf sound under the last shot.",
 title="Horseshoe Crabs Are Older Than Trees",
 desc="Horseshoe crab fossils go back 445 million years. The first forests? About 385 million. Facts That Sound Fake #1. Sources: Palaeontology (2008), Nature (2007).",
 tags=["facts","prehistoric","shorts"],
 comment="What else do you think was around before trees?",
 cta="Fact #2 is a tree that was alive before the Great Pyramid - and it's still growing.",
 loop="Final line 'still on our beaches' lands on the same low crab framing as frame 1, so the replay reads as continuous.",
 length="~20s", exp="Control: repeat the proven 'X older than Y' shape of the shark Short with a fresh animal", metric="Viewed vs swiped vs the shark Short's baseline"),

dict(day=1, n=2, cat="Earth / nature", hooktype="Comparison with a famous landmark",
 topic="A living tree older than the Great Pyramid",
 claim="Methuselah, a Great Basin bristlecone pine in California, is about 4,850 years old by tree-ring count (germinated ~2830 BC); the Great Pyramid was completed around 2560 BC.",
 sources=[("Conservation International: Methuselah","https://www.conservation.org/news/methuselah-still-the-worlds-oldest-tree"),
          ("EarthDate: Older Than Methuselah","https://www.earthdate.org/episodes/older-than-methuselah")],
 frame="Split frame: left, a twisted, half-dead bristlecone pine on a white rocky slope; right, the Great Pyramid. Text: ALIVE BEFORE THIS WAS BUILT, with an arrow to the pyramid.",
 hook="This tree was alive before the Great Pyramid was finished.",
 script=[("0.0-1.5","This tree was alive before the Great Pyramid was finished."),
         ("1.5-5.0","It's a bristlecone pine in California. People call it Methuselah."),
         ("5.0-15.0","Its rings put it at about 4,850 years old. The Great Pyramid was finished around 2560 BC - by then, this tree was already centuries old."),
         ("15.0-21.0","It's still alive. On a mountain, right now, growing.")],
 osd=[("0.0-1.5","ALIVE BEFORE\nTHE PYRAMID"),("1.5-5.0","Methuselah\nbristlecone pine"),("5.0-10.0","~4,850 years old"),
      ("10.0-15.0","pyramid done: ~2560 BC"),("15.0-21.0","still growing")],
 shots=[dict(t="0-1.5s", subj="Tree + pyramid split", comp="50/50 vertical split", move="Static, subtle parallax", light="Hard high-altitude sun", trans="Hard cut",
             prompt="an ancient twisted bristlecone pine on a white dolomite mountainside, half bare silver wood, deep blue high-altitude sky, "+V),
        dict(t="1.5-5s", subj="Bark and dead wood", comp="Extreme close-up, twisted grain", move="Slow crawl up the trunk", light="Side light, texture", trans="Crossfade",
             prompt="extreme close-up of twisted silver bristlecone pine wood with deep spiral grain and a thin strip of living bark, raking side light, "+V),
        dict(t="5-15s", subj="Pyramid under construction", comp="Wide, workers tiny", move="Slow drone push", light="Warm desert haze", trans="Match cut on silhouette",
             prompt="the Great Pyramid of Giza under construction around 2560 BC, ramps and thousands of workers tiny in the frame, warm desert haze, aerial view, "+V),
        dict(t="15-21s", subj="Tree at sunset", comp="Tree small against huge sky", move="Slow pull back", light="Sunset rim light", trans="Cut to frame 1",
             prompt="a lone ancient bristlecone pine silhouetted on a mountain ridge at sunset, vast sky, rim light on the gnarled branches, "+V)],
 sound="Wind at altitude, sparse single-note piano. Hit on 'Great Pyramid'. Low boom under 'already centuries old'.",
 title="This Tree Was Alive Before the Great Pyramid Was Finished",
 desc="Methuselah, a bristlecone pine in California, is about 4,850 years old. The Great Pyramid was finished around 2560 BC. Facts That Sound Fake #2.",
 tags=["facts","nature","history"],
 comment="What's the oldest thing you've ever touched?",
 cta="Fact #3 is a mountain that makes Everest look like a hill.",
 loop="Ends on the tree against the sky - the same tree as the opening split - so the loop is seamless.",
 length="~21s", exp="Nature fact with a human-made landmark as the comparison", metric="Average percentage viewed vs #1"),

dict(day=2, n=3, cat="Space", hooktype="Scale shock",
 topic="Olympus Mons is about two and a half times the height of Everest",
 claim="Olympus Mons on Mars rises about 21.9 km; Mount Everest is 8.85 km - Everest would not reach halfway up.",
 sources=[("Astronomy.com: Olympus Mons height","https://www.astronomy.com/science/olympus-mons-mars-mega-volcano-height-formation/"),
          ("NASA Photojournal: Olympus Mons","https://science.nasa.gov/photojournal/pj-olympus-mons-lava-flows-2/")],
 frame="Mount Everest shown tiny, drawn to scale beside a vast shield volcano whose peak leaves the top of the frame. Text: EVEREST IS TINY HERE.",
 hook="Everest wouldn't reach halfway up this mountain.",
 script=[("0.0-1.5","Everest wouldn't reach halfway up this mountain."),
         ("1.5-5.0","It's not on Earth. It's Olympus Mons, on Mars."),
         ("5.0-15.0","It rises about 21.9 kilometers. Everest is 8.8. Stack two and a half Everests and you're still roughly level."),
         ("15.0-20.0","And it's a volcano. The biggest we've found on any planet.")],
 osd=[("0.0-1.5","EVEREST = TINY"),("1.5-5.0","Olympus Mons, Mars"),("5.0-10.0","21.9 km"),("10.0-15.0","Everest: 8.8 km"),("15.0-20.0","a VOLCANO")],
 shots=[dict(t="0-1.5s", subj="Scale comparison", comp="Everest tiny bottom-left, volcano fills frame", move="Tilt up past the top", light="Flat, diagrammatic but real textures", trans="Hard cut",
             prompt="a photorealistic scale comparison: Mount Everest small at the bottom of the frame beside an enormous Martian shield volcano rising far above it, red dusty terrain, "+V),
        dict(t="1.5-5s", subj="Olympus Mons from orbit", comp="Caldera centered", move="Slow orbit", light="Low sun, long shadows", trans="Crossfade",
             prompt="Olympus Mons seen from Mars orbit, the huge summit caldera centered, long shadows, thin pink atmosphere at the horizon, "+V),
        dict(t="5-15s", subj="Stacked Everests", comp="Three mountains stacked vertically", move="Slow rise", light="Clean studio-like", trans="Whip up",
             prompt="three Mount Everest peaks stacked on top of each other beside a towering Martian volcano cliff, surreal but photorealistic, "+V),
        dict(t="15-20s", subj="Caldera rim at dusk", comp="Rim foreground, drop behind", move="Push over the edge", light="Blue Martian sunset", trans="Cut to frame 1",
             prompt="standing on the rim of the Olympus Mons caldera at a blue Martian sunset, vast drop into the crater, "+V)],
 sound="Wide cinematic pad, slow. A rising tone that climbs with the tilt in shot 1. Heavy hit on '21.9'.",
 title="Everest Wouldn't Reach Halfway Up This Mountain",
 desc="Olympus Mons on Mars rises about 21.9 km - roughly two and a half times Everest. Facts That Sound Fake #3.",
 tags=["space","mars","facts"],
 comment="Would you rather climb Everest or Olympus Mons?",
 cta="Fact #4 is happening in your own face right now - and you've never noticed.",
 loop="Final wide on the volcano returns to the scale shot's framing.",
 length="~20s", exp="Space category; scale comparison against a famous Earth landmark", metric="Viewed vs swiped (does space stop the scroll?)"),

dict(day=2, n=4, cat="Human body / psychology", hooktype="'Right now' - happening to the viewer",
 topic="Your brain edits your nose out of your vision",
 claim="Your nose is always in your field of view; the brain filters it out through neural adaptation and unconscious selective attention. Closing one eye makes it visible.",
 sources=[("Live Science: Why don't you usually see your nose?","https://www.livescience.com/health/why-dont-you-usually-see-your-nose"),
          ("CK-12: Why can't I see my nose?","https://www.ck12.org/flexi/life-science/vision/why-can't-i-see-my-nose/")],
 frame="A first-person view of a room with the soft blurred edge of a nose visible at the bottom-centre, circled in a thin highlight. Text: IT'S IN YOUR VIEW RIGHT NOW.",
 hook="Your nose is in your view right now.",
 script=[("0.0-1.5","Your nose is in your view right now."),
         ("1.5-5.0","You just don't see it. Your brain deletes it."),
         ("5.0-14.0","Anything that never changes, your brain stops reporting. Your nose never moves, so it gets filtered out - all day, every day."),
         ("14.0-19.0","Close one eye. There it is. It's been there your whole life.")],
 osd=[("0.0-1.5","YOUR NOSE\nIS HERE"),("1.5-5.0","your brain\ndeletes it"),("5.0-14.0","never changes =\nfiltered out"),("14.0-19.0","close one eye")],
 shots=[dict(t="0-1.5s", subj="POV with nose edge", comp="Nose blur bottom-centre", move="Static", light="Natural indoor", trans="Hard cut",
             prompt="first-person point of view looking at a sunlit living room, the soft out-of-focus edge of the viewer's own nose visible at the bottom centre, "+V),
        dict(t="1.5-5s", subj="Brain with a filter", comp="Stylized glowing brain", move="Slow rotate", light="Dark, blue glow", trans="Crossfade",
             prompt="a glowing translucent human brain in darkness with a soft light filter sweeping across it, scientific, "+V),
        dict(t="5-14s", subj="Eye close-up", comp="Macro iris", move="Push into pupil", light="Soft key", trans="Zoom through",
             prompt="extreme macro of a human eye, iris detail, soft key light, reflection of a room in the pupil, "+V),
        dict(t="14-19s", subj="POV one eye closed", comp="Same room, nose now clear", move="Static", light="Natural", trans="Cut to frame 1",
             prompt="first-person view of the same sunlit living room with one eye closed, the side of the nose clearly visible at the lower edge, "+V)],
 sound="Quiet, close, intimate. A soft 'blink' click when the eye closes. Minimal music.",
 title="Your Nose Is in Your View Right Now",
 desc="Your brain filters out your nose because it never changes. Close one eye and it appears. Facts That Sound Fake #4.",
 tags=["brain","facts","humanbody"],
 comment="Did you just close one eye? Be honest.",
 cta="Fact #5: the world's first webcam was built to watch... coffee.",
 loop="Ends on the same POV room as frame 1, so the replay asks the viewer to look again.",
 length="~19s", exp="Interactive 'try it now' hook - does a test-it-yourself raise shares?", metric="Shares and comments per 1,000 views"),

dict(day=3, n=5, cat="Technology", hooktype="Absurd origin story",
 topic="The first webcam watched a coffee pot",
 claim="In 1991 researchers at the University of Cambridge Computer Lab pointed a 128x128 greyscale camera at the Trojan Room coffee pot so they could see if coffee was left; it was connected to the web in 1993.",
 sources=[("Trojan Room coffee pot (Wikipedia, with primary refs)","https://en.wikipedia.org/wiki/Trojan_Room_coffee_pot"),
          ("Tom's Hardware: the world's first webcam","https://www.tomshardware.com/peripherals/webcams/the-worlds-first-webcam-was-switched-off-25-years-ago-today-128x128-grayscale-feed-predated-the-world-wide-web-to-monitor-a-cambridge-coffee-pot")],
 frame="A grainy black-and-white, pixelated image of a coffee pot, like an early low-res camera feed, with a red REC dot. Text: THE FIRST WEBCAM.",
 hook="The first webcam was built to watch a coffee pot.",
 script=[("0.0-1.5","The first webcam was built to watch a coffee pot."),
         ("1.5-5.0","Cambridge, 1991. Scientists kept walking to the coffee room and finding the pot empty."),
         ("5.0-15.0","So they pointed a camera at the pot. 128 by 128 pixels, black and white, checked from their desks."),
         ("15.0-20.0","In 1993, it went on the web. The first webcam wasn't for security. It was for coffee.")],
 osd=[("0.0-1.5","THE FIRST\nWEBCAM"),("1.5-5.0","Cambridge, 1991"),("5.0-15.0","128 x 128 pixels"),("15.0-20.0","1993: on the web")],
 shots=[dict(t="0-1.5s", subj="Low-res coffee pot feed", comp="Pot centered, scanlines", move="Static, slight flicker", light="Greyscale", trans="Hard cut",
             prompt="a grainy low-resolution black and white security-camera style image of a glass coffee pot on a warmer in an office corridor, pixelated, "+V),
        dict(t="1.5-5s", subj="1991 computer lab", comp="Wide, beige computers", move="Slow dolly", light="Fluorescent", trans="Crossfade",
             prompt="a 1991 university computer laboratory with beige CRT monitors and cables, fluorescent light, researchers at desks, "+V),
        dict(t="5-15s", subj="Camera aimed at pot", comp="Over-the-shoulder of the camera", move="Push-in", light="Office light", trans="Match cut to CRT",
             prompt="an old video camera on a tripod pointed at a coffee pot in a small office kitchen, 1990s, "+V),
        dict(t="15-20s", subj="CRT showing the pot", comp="Screen fills frame", move="Slow push into screen", light="CRT glow", trans="Cut to frame 1",
             prompt="an early 1990s CRT monitor displaying a tiny grey image of a coffee pot, glowing in a dim room, "+V)],
 sound="Lo-fi, playful synth. A small 'shutter' click on the first frame; a coffee-pour sound under the last line.",
 title="The First Webcam Was Built to Watch a Coffee Pot",
 desc="In 1991, Cambridge researchers aimed a camera at their coffee pot so they could see if it was empty. It went online in 1993. Facts That Sound Fake #5.",
 tags=["tech","history","facts"],
 comment="What's the laziest invention you'd build?",
 cta="Fact #6: an animal that makes heat close to the surface of the Sun.",
 loop="Final CRT image is the same pot as the grainy first frame.",
 length="~20s", exp="Tech + humour - does a funny origin beat an awe fact on comments?", metric="Comments per 1,000 views"),

dict(day=3, n=6, cat="Animal", hooktype="Impossible property",
 topic="The pistol shrimp makes a bubble nearly as hot as the Sun's surface",
 claim="A snapping (pistol) shrimp's claw snaps so fast it forms a cavitation bubble; its collapse emits light implying at least ~5,000 K - the Sun's visible surface is ~5,800 K.",
 sources=[("Lohse, Schmitz & Versluis 2001, Nature: Snapping shrimp make flashing bubbles","https://www.nature.com/articles/35097152"),
          ("Science News: Shrimps spew bubbles as hot as the sun","https://www.sciencenews.org/article/shrimps-spew-bubbles-hot-sun")],
 note="Say 'nearly as hot' - the 5,000 K figure is a lower bound and sits just under the Sun's surface temperature.",
 frame="A macro shot of a small shrimp's oversized claw, mid-snap, with a bright white flash of light in a bubble in front of it. Text: HOT AS THE SUN?",
 hook="This shrimp makes heat close to the surface of the Sun.",
 script=[("0.0-1.5","This shrimp makes heat close to the surface of the Sun."),
         ("1.5-5.0","It's called a pistol shrimp, and its weapon is one oversized claw."),
         ("5.0-15.0","It snaps so fast it makes a bubble. When the bubble collapses, it flashes - at least 5,000 kelvin inside. The Sun's surface is about 5,800."),
         ("15.0-20.0","The shockwave stuns its prey. It hunts with a bubble.")],
 osd=[("0.0-1.5","NEAR SUN-HOT"),("1.5-5.0","pistol shrimp"),("5.0-11.0","bubble: 5,000+ K"),("11.0-15.0","Sun's surface: ~5,800 K"),("15.0-20.0","it hunts\nwith a bubble")],
 shots=[dict(t="0-1.5s", subj="Claw mid-snap", comp="Macro, claw fills frame", move="Speed ramp", light="Underwater, dark", trans="Hard cut with flash",
             prompt="macro underwater shot of a pistol shrimp with one oversized claw snapping shut, a tiny bright flash of light inside a collapsing bubble, dark water, "+V),
        dict(t="1.5-5s", subj="Shrimp on reef", comp="Shrimp small, reef around", move="Slow orbit", light="Blue reef light", trans="Crossfade",
             prompt="a small pistol shrimp on a coral reef with one huge claw, blue underwater light, "+V),
        dict(t="5-15s", subj="Collapsing bubble", comp="Bubble centered", move="Extreme slow motion", light="Flash of white", trans="Flash cut",
             prompt="an extreme slow motion cavitation bubble collapsing underwater with a point of white-hot light at its centre, "+V),
        dict(t="15-20s", subj="Sun surface", comp="Sun's granulated surface", move="Slow drift", light="Orange-white plasma", trans="Cut to frame 1",
             prompt="the surface of the Sun in close detail, granulated orange-white plasma, solar texture, "+V)],
 sound="Tense low pulse. A sharp 'crack' at 0.9s timed to the snap. Muffled underwater bed.",
 title="This Shrimp Makes Heat Close to the Sun's Surface",
 desc="A pistol shrimp's snap creates a bubble that collapses at 5,000+ kelvin - near the Sun's ~5,800 K surface. Facts That Sound Fake #6. Source: Nature (2001).",
 tags=["animals","ocean","facts"],
 comment="Which animal would win: pistol shrimp or mantis shrimp?",
 cta="Fact #7: dinosaurs had shorter days than you.",
 loop="The Sun's surface cuts back to the flash in the bubble - light to light.",
 length="~20s", exp="Animal 'impossible power' with a sound-synced visual hook", metric="Viewed vs swiped (does a flash on frame 1 help?)"),

dict(day=4, n=7, cat="Earth / prehistoric", hooktype="Contradicts something 'fixed'",
 topic="Days were about 23.5 hours long near the end of the dinosaurs",
 claim="Growth rings in a 70-million-year-old rudist clam show a year had about 372 days and a day about 23.5 hours; Earth's rotation has slowed since.",
 sources=[("AGU press release: days were half-hour shorter 70 million years ago","https://news.agu.org/press-release/ancient-shell-shows-days-were-half-hour-shorter-70-million-years-ago/"),
          ("ScienceDaily summary","https://www.sciencedaily.com/releases/2020/03/200309135410.htm")],
 frame="A T. rex silhouette under a sky with a clock face overlaid showing 23:30. Text: A DAY WAS 23.5 HOURS.",
 hook="Dinosaurs had shorter days than you do.",
 script=[("0.0-1.5","Dinosaurs had shorter days than you do."),
         ("1.5-5.0","Seventy million years ago, a day lasted about 23 and a half hours."),
         ("5.0-15.0","A fossil clam grew one ring a day, the way trees grow one a year. Count a year's rings: 372 days."),
         ("15.0-20.0","Earth has been slowing ever since. Your days are still getting longer - very slowly.")],
 osd=[("0.0-1.5","SHORTER DAYS"),("1.5-5.0","1 day = 23.5 hrs"),("5.0-11.0","a clam grew\na ring a day"),("11.0-15.0","372 days a year"),("15.0-20.0","still slowing")],
 shots=[dict(t="0-1.5s", subj="T. rex at dusk", comp="Silhouette, big sky", move="Slow push", light="Fast-moving dusk", trans="Hard cut",
             prompt="a Tyrannosaurus rex silhouetted against a dramatic late Cretaceous sunset sky, moving clouds, "+V),
        dict(t="1.5-5s", subj="Timelapse sky", comp="Horizon", move="Timelapse", light="Day to night", trans="Crossfade",
             prompt="a prehistoric landscape timelapse from day to night, fast moving clouds and sun arc, "+V),
        dict(t="5-15s", subj="Fossil clam rings", comp="Macro of shell layers", move="Slow track along rings", light="Raking light", trans="Match cut",
             prompt="macro of a fossil clam shell cross-section showing fine daily growth rings, raking light, "+V),
        dict(t="15-20s", subj="Earth from space", comp="Earth rotating", move="Slow rotation", light="Terminator line", trans="Cut to frame 1",
             prompt="planet Earth rotating slowly in space with the day-night terminator line, the Moon in the distance, "+V)],
 sound="Ticking clock slightly fast, then slows on the last line. Deep hit on '23 and a half'.",
 title="Dinosaurs Had Shorter Days Than You Do",
 desc="A 70-million-year-old clam shows a day lasted about 23.5 hours and a year had 372 days. Facts That Sound Fake #7. Source: AGU (2020).",
 tags=["dinosaurs","earth","facts"],
 comment="What would you do with the extra half hour?",
 cta="Fact #8: an animal that survived being put into open space.",
 loop="The slowing clock tick at the end matches the tick under the opening.",
 length="~20s", exp="Earth fact framed as a comparison to the viewer ('than you')", metric="Average percentage viewed"),

dict(day=4, n=8, cat="Animal / space", hooktype="Survived the impossible",
 topic="Tardigrades survived open space",
 claim="In 2007 (ESA FOTON-M3), dried tardigrades spent 10 days exposed to space vacuum in low Earth orbit; vacuum-only groups survived at rates close to controls, and some survived vacuum plus solar UV.",
 sources=[("Jonsson et al. 2008, Current Biology","https://www.cell.com/current-biology/fulltext/S0960-9822(08)00805-1")],
 frame="A tardigrade (water bear) floating in black space with Earth's curve behind it. Text: SURVIVED SPACE.",
 hook="This animal survived the vacuum of space.",
 script=[("0.0-1.5","This animal survived the vacuum of space."),
         ("1.5-5.0","It's a tardigrade. A water bear. Smaller than a grain of salt."),
         ("5.0-15.0","In 2007, scientists sent dried tardigrades into orbit - outside the spacecraft. Ten days of vacuum. Back on Earth, they added water."),
         ("15.0-20.0","The ones shielded from the Sun's radiation survived about as well as ones that never left.")],
 osd=[("0.0-1.5","SURVIVED SPACE"),("1.5-5.0","tardigrade"),("5.0-11.0","10 days in vacuum"),("11.0-15.0","add water..."),("15.0-20.0","still alive")],
 shots=[dict(t="0-1.5s", subj="Tardigrade in space", comp="Animal centered, Earth curve behind", move="Slow spin", light="Hard sunlight", trans="Hard cut",
             prompt="a microscopic tardigrade water bear floating in the black of space with the curve of Earth behind it, hard sunlight, "+V),
        dict(t="1.5-5s", subj="Tardigrade on moss", comp="Macro", move="Push-in", light="Microscope light", trans="Crossfade",
             prompt="electron microscope style image of a tardigrade crawling on green moss, detailed, "+V),
        dict(t="5-15s", subj="Capsule in orbit", comp="Capsule small, Earth large", move="Slow orbit", light="Orbital sunrise", trans="Whip",
             prompt="a small unmanned research capsule orbiting Earth with an open experiment tray exposed to space, orbital sunrise, "+V),
        dict(t="15-20s", subj="Water drop revives", comp="Macro drop", move="Slow motion", light="Soft", trans="Cut to frame 1",
             prompt="a single drop of water falling onto a dried tardigrade under a microscope, the animal beginning to move, "+V)],
 sound="Near-silence of space; one soft heartbeat thump when water hits. Airy pad.",
 title="This Animal Survived the Vacuum of Space",
 desc="In 2007, dried tardigrades spent 10 days exposed to space. Many revived with water. Facts That Sound Fake #8. Source: Current Biology (2008).",
 tags=["space","animals","science"],
 comment="Would you trust a tardigrade to survive the apocalypse?",
 cta="Fact #9: you are shorter right now than when you woke up.",
 loop="Revived tardigrade drifts back into the opening space frame.",
 length="~20s", exp="Space-animal crossover", metric="Subscribers gained per 1,000 views"),

dict(day=5, n=9, cat="Human body", hooktype="About the viewer's own body, testable",
 topic="You're shorter in the evening than in the morning",
 claim="Spinal discs compress under gravity during the day and rehydrate overnight; most people are about 1-2 cm taller in the morning.",
 sources=[("Rhode Island Limb (orthotics clinic): why you're taller in the morning","https://www.rilimb.com/2013/08/20/why-am-i-taller-in-the-morning/"),
          ("Ira Studios: spinal disc compression explained","https://irastudios.org/why-you-are-taller-in-the-morning-explained-with-3d-visuals/")],
 note="Sources found are clinical/educational, not peer-reviewed. The effect is standard spine physiology; confirm the 1-2 cm figure against a medical reference before publishing.",
 frame="A person standing against a height chart, with a ghosted outline of them slightly taller above their head. Text: SHORTER THAN THIS MORNING.",
 hook="You're shorter right now than when you woke up.",
 script=[("0.0-1.5","You're shorter right now than when you woke up."),
         ("1.5-5.0","Not a little. A measurable amount."),
         ("5.0-15.0","Between your vertebrae are discs, soft and full of fluid. All day, gravity squeezes them. Most people lose one to two centimeters by evening."),
         ("15.0-20.0","Sleep lying down, and they refill. Measure yourself tonight. Then again in the morning.")],
 osd=[("0.0-1.5","SHORTER NOW"),("1.5-5.0","measurably"),("5.0-11.0","spinal discs\nsqueeze all day"),("11.0-15.0","1-2 cm lost"),("15.0-20.0","measure tonight\n+ tomorrow")],
 shots=[dict(t="0-1.5s", subj="Height chart", comp="Person against wall chart, ghost outline", move="Static", light="Bright bathroom", trans="Hard cut",
             prompt="a person standing against a wall height chart with a faint ghosted outline of themselves slightly taller above their head, bright clean light, "+V),
        dict(t="1.5-5s", subj="Morning stretch", comp="Silhouette in window", move="Slow push", light="Morning sun", trans="Crossfade",
             prompt="a person stretching in bed at sunrise, silhouette against a bright window, "+V),
        dict(t="5-15s", subj="Spine discs", comp="Anatomical close-up", move="Slow compress animation", light="Medical blue", trans="Zoom",
             prompt="an anatomical 3D render of spinal vertebrae with intervertebral discs slowly compressing, medical blue lighting, "+V),
        dict(t="15-20s", subj="Tape measure", comp="Tape against wall", move="Pull-back", light="Warm evening lamp", trans="Cut to frame 1",
             prompt="a tape measure against a wall marking a person's height in the evening, warm lamp light, "+V)],
 sound="Bright, light pluck melody. A tiny 'shrink' whoosh under 'squeezes them'.",
 title="You're Shorter Right Now Than When You Woke Up",
 desc="Gravity compresses the discs in your spine during the day. Most people are 1-2 cm taller in the morning. Facts That Sound Fake #9.",
 tags=["humanbody","facts","health"],
 comment="Measure tonight and tomorrow - how much did you lose?",
 cta="Fact #10: an animal with no stomach at all.",
 loop="Tape-measure shot returns to the height chart of frame 1.",
 length="~20s", exp="Body fact with a 24-hour self-test - drives returning viewers", metric="Comments containing a measurement; returning viewers"),

dict(day=5, n=10, cat="Animal", hooktype="Missing body part",
 topic="The platypus has no stomach",
 claim="The platypus has no functional stomach - its gullet connects almost directly to its intestine; genes for gastric acid and pepsin were deleted or inactivated during its evolution.",
 sources=[("Ordonez et al. 2008, Genome Biology: loss of gastric genes in platypus","https://link.springer.com/article/10.1186/gb-2008-9-5-r81"),
          ("National Geographic: how the platypus lost its stomach","https://www.nationalgeographic.com/science/article/how-the-platypus-and-a-quarter-of-fishes-lost-their-stomachs")],
 frame="A platypus swimming, with a simple translucent X-ray overlay showing a straight tube from throat to gut and a crossed-out stomach shape. Text: NO STOMACH.",
 hook="This animal has no stomach.",
 script=[("0.0-1.2","This animal has no stomach."),
         ("1.2-5.0","A platypus. Its food goes from its throat almost straight into its intestine."),
         ("5.0-15.0","Somewhere in its evolution it lost the genes that make stomach acid and digestive enzymes. Scientists found them deleted or switched off in its DNA."),
         ("15.0-20.0","And it's not alone. About a quarter of fish species don't have a true stomach either.")],
 osd=[("0.0-1.2","NO STOMACH"),("1.2-5.0","throat -> intestine"),("5.0-15.0","stomach genes:\ndeleted"),("15.0-20.0","~1/4 of fish too")],
 shots=[dict(t="0-1.2s", subj="Platypus with X-ray overlay", comp="Side profile", move="Slow glide", light="River light", trans="Hard cut",
             prompt="a platypus swimming in a clear freshwater river, side profile, sunlight dappling through the water, "+V),
        dict(t="1.2-5s", subj="Platypus foraging", comp="Close, bill in gravel", move="Tracking", light="Murky green", trans="Crossfade",
             prompt="a platypus foraging along a riverbed with its bill in the gravel, murky green underwater light, "+V),
        dict(t="5-15s", subj="DNA strand", comp="Helix with gaps", move="Slow rotate", light="Dark lab glow", trans="Zoom",
             prompt="a glowing DNA double helix with a few segments missing, dark laboratory background, "+V),
        dict(t="15-20s", subj="School of fish", comp="Fish filling frame", move="Swim-through", light="Blue ocean", trans="Cut to frame 1",
             prompt="a dense school of silver fish in blue ocean water, "+V)],
 sound="Quirky, bouncy bass. A comic 'record-scratch'-free pause on 'no stomach' (silence then music back).",
 title="The Platypus Has No Stomach",
 desc="The platypus's gullet connects almost straight to its intestine - it lost its stomach genes. Facts That Sound Fake #10. Source: Genome Biology (2008).",
 tags=["animals","facts","nature"],
 comment="Which body part could you live without?",
 cta="Fact #11: a jellyfish that can turn itself back into a baby.",
 loop="The fish shot cuts back to the platypus underwater - water to water.",
 length="~20s", exp="Bizarre-animal category", metric="Viewed vs swiped vs #6 (other animal)"),

dict(day=6, n=11, cat="Animal", hooktype="Reverses something 'one way'",
 topic="A jellyfish that can reverse its own ageing",
 claim="Turritopsis dohrnii can revert from its adult (medusa) stage back to a juvenile polyp through cellular transdifferentiation; it is called biologically immortal, though it can still be eaten or die of disease.",
 sources=[("Matsumoto et al. 2019 (PMC): reverse development in T. dohrnii","https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6893190/"),
          ("MarineBio: Immortal jellyfish","https://www.marinebio.org/species/immortal-jellyfishes/turritopsis-dohrnii/")],
 note="Say 'doesn't have to die of old age', not 'can't die'.",
 frame="A tiny glowing red-centred jellyfish in black water, with a rewind symbol faintly overlaid. Text: IT AGES BACKWARDS.",
 hook="This jellyfish can turn back into a baby.",
 script=[("0.0-1.5","This jellyfish can turn back into a baby."),
         ("1.5-5.0","When it's injured or starving, the adult sinks to the seabed."),
         ("5.0-15.0","It turns into a blob of cells, regrows as a polyp, its baby form, and grows up again. Biologically immortal."),
         ("15.0-20.0","It can still be eaten. It can still get sick. It just doesn't have to die of old age.")],
 osd=[("0.0-1.5","AGES BACKWARDS"),("1.5-5.0","injured? starving?"),("5.0-11.0","adult -> blob -> baby"),("11.0-15.0","'biologically immortal'"),("15.0-20.0","no death\nfrom old age")],
 shots=[dict(t="0-1.5s", subj="Turritopsis jellyfish", comp="Centered, tiny, glowing", move="Slow pulse", light="Black water, backlit", trans="Hard cut",
             prompt="a tiny translucent immortal jellyfish with a bright red centre pulsing in pitch-black water, backlit, "+V),
        dict(t="1.5-5s", subj="Jellyfish sinking", comp="Top to bottom", move="Slow descent", light="Dim", trans="Crossfade",
             prompt="a small translucent jellyfish slowly sinking toward a dark seabed, dim light, "+V),
        dict(t="5-15s", subj="Cell blob to polyp", comp="Macro seabed", move="Timelapse", light="Microscope glow", trans="Morph",
             prompt="macro timelapse of a cluster of cells on a seabed growing into a small branching polyp, microscope lighting, "+V),
        dict(t="15-20s", subj="New jellyfish released", comp="Small medusae rising", move="Slow rise", light="Soft blue", trans="Cut to frame 1",
             prompt="tiny newborn jellyfish detaching from a polyp and drifting upward in soft blue water, "+V)],
 sound="Reversed piano swells (literal 'rewind'). A soft reverse-cymbal on 'back into a baby'.",
 title="This Jellyfish Can Turn Back Into a Baby",
 desc="Turritopsis dohrnii can revert from adult to its juvenile polyp stage - it doesn't have to die of old age. Facts That Sound Fake #11.",
 tags=["ocean","animals","facts"],
 comment="If you could restart one year of your life, which one?",
 cta="Fact #12: footprints that could last millions of years.",
 loop="Newborn jellyfish rising becomes the adult in the opening frame - literally a loop.",
 length="~20s", exp="Emotional-hook animal fact; comment question about the viewer's own life", metric="Comments per 1,000 views"),

dict(day=6, n=12, cat="Space", hooktype="Permanence / 'still there'",
 topic="The Apollo footprints could last millions of years",
 claim="With no wind or rain on the Moon, Apollo bootprints are expected to persist for millions of years; only slow micrometeorite 'gardening' erodes them. NASA's Lunar Reconnaissance Orbiter has imaged the astronauts' trails.",
 sources=[("NASA StarChild: Apollo 11","https://starchild.gsfc.nasa.gov/docs/StarChild/space_level1/apollo11.html"),
          ("ScienceBlog summary of lunar surface preservation","https://scienceblog.com/m-no-wind-stirs-the-moon-and-no-rain-falls-there-and-that-stillness-has-a-strange-consequence-the-bootprints-apollo-astronauts-pressed-into-the-grey-dust-over-fifty-years-ago-will-likely-stay-crisp-an/")],
 frame="A sharp bootprint in grey lunar dust, Earth rising on the horizon. Text: STILL THERE.",
 hook="These footprints could still be here in millions of years.",
 script=[("0.0-1.5","These footprints could still be here in millions of years."),
         ("1.5-5.0","They're on the Moon. Left by Apollo astronauts more than 50 years ago."),
         ("5.0-15.0","The Moon has no wind and no rain. Nothing to blow them away. The only thing wearing them down is a slow drizzle of tiny meteorites."),
         ("15.0-20.0","NASA's orbiter has photographed the paths they walked. Still visible.")],
 osd=[("0.0-1.5","STILL THERE"),("1.5-5.0","Apollo, 50+ years ago"),("5.0-11.0","no wind. no rain."),("11.0-15.0","eroding: very slowly"),("15.0-20.0","seen from orbit")],
 shots=[dict(t="0-1.5s", subj="Bootprint", comp="Macro, print fills frame", move="Slow push", light="Harsh sun, black sky", trans="Hard cut",
             prompt="a sharp astronaut bootprint pressed into grey lunar dust, harsh sunlight, black sky, Earth rising on the horizon, "+V),
        dict(t="1.5-5s", subj="Lunar module on surface", comp="Wide, module small", move="Slow pan", light="Hard lunar light", trans="Crossfade",
             prompt="an Apollo lunar module standing on the grey Moon surface with footprint trails around it, black sky, "+V),
        dict(t="5-15s", subj="Micrometeorite dust", comp="Dust grains close-up", move="Slow motion", light="Low sun", trans="Zoom",
             prompt="macro of lunar regolith dust grains with tiny specks of micrometeorite impact, low raking sunlight, "+V),
        dict(t="15-20s", subj="Orbital view of trails", comp="Top-down grainy", move="Slow drift", light="Satellite", trans="Cut to frame 1",
             prompt="a top-down orbital satellite image of the Moon surface showing faint trails of footprints around a landing site, "+V)],
 sound="Vast silence with a faint radio crackle; slow cinematic swell. No hit - stillness is the mood.",
 title="The Apollo Footprints Could Last Millions of Years",
 desc="With no wind or rain, the Apollo bootprints on the Moon should persist for millions of years. Facts That Sound Fake #12.",
 tags=["space","moon","facts"],
 comment="What would you leave behind on the Moon?",
 cta="Fact #13: an animal that survived the asteroid that killed the dinosaurs.",
 loop="The orbital trail shot resolves back into the single bootprint.",
 length="~20s", exp="Quiet, awe-toned hook vs the loud hooks elsewhere", metric="Average view duration"),

dict(day=7, n=13, cat="Prehistoric / animal", hooktype="Survivor of a famous catastrophe",
 topic="Crocodiles survived the asteroid that killed the dinosaurs",
 claim="Crocodilians survived the K-Pg extinction 66 million years ago, likely helped by a low metabolism (months without food) and life in freshwater habitats less affected by the collapse of land plants.",
 sources=[("ABC Education: how crocodiles survived the asteroid","https://www.abc.net.au/education/how-crocodiles-survived-the-asteroid-that-killed-the-dinosaurs/13668262"),
          ("The Conversation: how did crocodiles survive?","https://theconversation.com/curious-kids-how-did-crocodiles-survive-the-asteroid-that-killed-the-dinosaurs-172390")],
 frame="A crocodile's eyes just above dark water, with a burning asteroid streak in the sky behind. Text: IT SURVIVED THIS.",
 hook="Crocodiles survived the asteroid that killed T. rex.",
 script=[("0.0-1.5","Crocodiles survived the asteroid that killed T. rex."),
         ("1.5-5.0","Sixty-six million years ago, the impact wiped out most large animals on land."),
         ("5.0-15.0","Crocodiles made it. Two reasons: they can go months without eating, and they lived in rivers and swamps, where food lasted longer after the plants died."),
         ("15.0-20.0","The dinosaurs burned too fast. The crocodiles waited it out.")],
 osd=[("0.0-1.5","IT SURVIVED THIS"),("1.5-5.0","66 million yrs ago"),("5.0-10.0","months without food"),("10.0-15.0","rivers + swamps"),("15.0-20.0","waited it out")],
 shots=[dict(t="0-1.5s", subj="Croc eyes + asteroid", comp="Eyes at waterline, sky behind", move="Slow push", light="Fiery sky reflection", trans="Hard cut",
             prompt="a crocodile's eyes just above dark swamp water at night, a burning asteroid streaking across the sky reflected in the water, "+V),
        dict(t="1.5-5s", subj="Impact", comp="Wide horizon", move="Shockwave", light="Blinding flash", trans="Flash",
             prompt="an asteroid impact on the horizon of a Cretaceous landscape, a massive fireball and shockwave, "+V),
        dict(t="5-15s", subj="Croc resting in murky river", comp="Low, still", move="Very slow", light="Grey ash-dimmed sun", trans="Crossfade",
             prompt="a crocodile resting motionless in a murky river under a grey ash-darkened sky, "+V),
        dict(t="15-20s", subj="Modern crocodile", comp="Close profile", move="Slow push", light="Golden hour", trans="Cut to frame 1",
             prompt="a modern crocodile basking on a riverbank at golden hour, close profile, "+V)],
 sound="Deep rumble building to an impact boom at ~2s, then muffled calm. Slow heartbeat under 'waited it out'.",
 title="Crocodiles Survived the Asteroid That Killed T. Rex",
 desc="Crocodiles made it through the extinction 66 million years ago - slow metabolisms and river habitats helped. Facts That Sound Fake #13.",
 tags=["dinosaurs","animals","facts"],
 comment="Which animal alive today would survive the next asteroid?",
 cta="Fact #14: look at a clock and the first second will freeze.",
 loop="Modern croc close-up mirrors the eyes-at-waterline opener.",
 length="~20s", exp="'Survivor' framing of a famous event", metric="Shares per 1,000 views"),

dict(day=7, n=14, cat="Psychology", hooktype="Instruction the viewer does immediately",
 topic="The stopped-clock illusion",
 claim="When you shift your gaze to a clock, the second hand's first tick seems to last longer than a second (chronostasis): the brain back-dates what you land on to cover the moment your eyes were moving.",
 sources=[("Yarrow et al. 2001, Nature: illusory perceptions of space and time","https://www.nature.com/articles/35104551"),
          ("Chronostasis (overview with references)","https://en.wikipedia.org/wiki/Chronostasis")],
 frame="An analogue wall clock, second hand frozen mid-tick, slightly motion-blurred edges around it. Text: LOOK AT A CLOCK.",
 hook="Look at a clock. The first second will freeze.",
 script=[("0.0-1.5","Look at a clock. The first second will freeze."),
         ("1.5-5.0","That tick takes too long. You're not imagining it."),
         ("5.0-15.0","When your eyes jump, the world blurs. Your brain hides that - and fills the gap by stretching what you land on backwards in time. It's called chronostasis."),
         ("15.0-20.0","Try it on the next clock you see. Then look back here.")],
 osd=[("0.0-1.5","LOOK AT A CLOCK"),("1.5-5.0","the tick is too long"),("5.0-11.0","your brain\nfills the gap"),("11.0-15.0","chronostasis"),("15.0-20.0","try it")],
 shots=[dict(t="0-1.5s", subj="Clock, frozen hand", comp="Clock centered", move="Static then snap", light="Clean daylight", trans="Hard cut",
             prompt="a classic analogue wall clock with the second hand caught mid-tick, clean daylight, minimal wall, "+V),
        dict(t="1.5-5s", subj="Eye darting", comp="Macro eye", move="Quick saccade", light="Soft key", trans="Whip",
             prompt="extreme macro of a human eye quickly darting to the side, soft key light, "+V),
        dict(t="5-15s", subj="Blurred room", comp="POV smear", move="Motion blur", light="Natural", trans="Snap into focus",
             prompt="a first-person motion-blurred view of a room as the eyes move, then snapping into sharp focus on a clock, "+V),
        dict(t="15-20s", subj="Clock ticking normally", comp="Same clock", move="Static", light="Daylight", trans="Cut to frame 1",
             prompt="the same analogue wall clock ticking normally, clean daylight, "+V)],
 sound="Loud, isolated clock tick; on the first tick hold 0.4s of silence (the 'freeze') before the next.",
 title="Look at a Clock - The First Second Freezes",
 desc="Chronostasis: your brain back-fills the moment your eyes move, so the first tick seems to last too long. Facts That Sound Fake #14. Source: Nature (2001).",
 tags=["brain","psychology","facts"],
 comment="Did it freeze for you? Yes or no.",
 cta="That's the first 14. Week two starts right after - and #15 sounds the most fake yet.",
 loop="Ends on the clock and 'look back here' - replaying the Short is the test.",
 length="~20s", exp="Interactive psychology hook with an audio 'freeze'", metric="Viewed vs swiped + rewatch (% viewed > 100)"),
]
