# -*- coding: utf-8 -*-
# History That Explains the World - "Older Than You Think" - 14 Shorts.
# The channel's measured best: the past doing something we assume is modern.

V = "vertical 9:16, photorealistic historical reconstruction, cinematic, natural period lighting, shallow depth of field, no text, no watermark, no modern objects"

def S(t, subj, comp, move, light, trans, prompt):
    return dict(t=t, subj=subj, comp=comp, move=move, light=light, trans=trans, prompt=prompt + ", " + V)

SHORTS = [
dict(day=1, n=1, cat="Ancient technology", hooktype="Modern word for an ancient object",
 topic="The Antikythera mechanism",
 claim="The Antikythera mechanism, recovered from a Greek shipwreck in 1901 and dated to roughly the 2nd-1st century BC, is a hand-cranked device with at least 30 surviving bronze gears that modelled the Sun and Moon, the Moon's phases, and predicted eclipses.",
 sources=[("Freeth et al. 2006, Nature 444 - Decoding the Antikythera Mechanism","https://www.nature.com/articles/nature05357"),
          ("Freeth et al. 2021, Scientific Reports - A model of the Cosmos in the Antikythera Mechanism","https://www.nature.com/articles/s41598-021-84310-w")],
 note="Dating is debated (proposals range from about 205 BC to about 60 BC). Say '2,000 years ago' or 'over 2,000 years ago', not an exact year.",
 frame="A corroded green bronze lump with gear teeth visible, lit like a museum object, with a faint glowing reconstruction of interlocking gears overlaid behind it. Text: 2,000-YEAR-OLD COMPUTER.",
 hook="This machine predicted eclipses over 2,000 years ago.",
 script=[("0.0-1.8","This machine predicted eclipses over 2,000 years ago."),
         ("1.8-5.0","Sponge divers found it in a Greek shipwreck in 1901."),
         ("5.0-15.0","X-rays revealed at least 30 gears. Turn a handle and it tracked the Sun, the Moon's phases, and coming eclipses. Nothing this complex appears again for over a thousand years."),
         ("15.0-20.0","It's often called the first computer.")],
 osd=[("0.0-1.8","2,000-YEAR-OLD\nCOMPUTER"),("1.8-5.0","found: 1901, shipwreck"),("5.0-10.0","30+ bronze gears"),("10.0-15.0","predicted eclipses"),("15.0-20.0","on the seabed")],
 shots=[S("0-1.8s","Corroded bronze fragment","Object centered, dark ground","Slow push","Museum spotlight","Hard cut","a corroded green bronze fragment of the Antikythera mechanism with visible gear teeth, museum spotlight on black"),
        S("1.8-5s","Divers at a wreck","Divers tiny over amphorae","Slow descent","Blue shafts of light","Crossfade","early 1900s sponge divers descending onto an ancient Greek shipwreck scattered with amphorae, blue underwater light shafts"),
        S("5-15s","Reconstructed gear train","Gears fill frame","Slow rotate","Warm bronze glow","Match cut","a gleaming reconstructed bronze gear train with dozens of interlocking hand-cut gears turning, warm glow"),
        S("15-20s","Wreck site, object on seabed","Seabed","Slow push","Dim blue","Cut to frame 1","a bronze object half-buried in sand on a dim seabed among broken amphorae")],
 sound="Deep underwater ambience, then precise clockwork ticking as the gears appear. Resonant low note on 'first computer'.",
 title="This Greek Machine With 30 Gears Predicted Eclipses 2,000 Years Ago",
 desc="The Antikythera mechanism: at least 30 bronze gears, and it predicted eclipses over 2,000 years ago. Older Than You Think #1. Sources: Nature (2006); Scientific Reports (2021).",
 tags=["history","ancientgreece","technology"],
 comment="What else do you think the ancients knew that we forgot?",
 cta="#2: Rome had apartment blocks - and a height limit, because they kept falling down.",
 loop="The object on the seabed cuts back to the same fragment under the museum light.",
 length="~20s", exp="Control: 'ancient = modern' (the channel's best subs/1k pattern)", metric="Subscribers per 1,000 views"),

dict(day=1, n=2, cat="Rome", hooktype="Modern thing in Rome",
 topic="Roman apartment blocks (insulae) and a height limit",
 claim="Most of Rome's urban population lived in multi-storey apartment blocks called insulae; after frequent collapses and fires, Augustus limited building height to 70 Roman feet (about 21 m). Upper floors were the cheapest.",
 sources=[("Insula (Roman building) - overview with references","https://en.wikipedia.org/wiki/Insula_(building)"),
          ("Strabo, Geography 5.3.7 (primary source for the Augustan height limit)",None)],
 frame="A narrow Roman street at dawn, towering five- and six-storey brick apartment blocks leaning over it, laundry between balconies. Text: ROME HAD APARTMENTS.",
 hook="Most people in ancient Rome lived in apartments.",
 script=[("0.0-1.5","Most people in ancient Rome lived in apartments."),
         ("1.5-5.0","Blocks called insulae: shops on the ground floor, families stacked above."),
         ("5.0-15.0","Built cheap and tall, they kept collapsing and burning. So Augustus set a height limit: 70 Roman feet, about 21 meters. The top floors, hardest to escape, were the cheapest."),
         ("15.0-21.0","In Rome, the penthouse was the budget option.")],
 osd=[("0.0-1.5","ROME HAD\nAPARTMENTS"),("1.5-5.0","insulae"),("5.0-10.0","collapses + fires"),("10.0-15.0","limit: 70 Roman ft"),("15.0-21.0","penthouse = cheapest")],
 shots=[S("0-1.5s","Roman street with tall blocks","Low angle up the street","Slow tilt up","Dawn, warm brick","Hard cut","a narrow ancient Roman street at dawn with towering five and six storey brick apartment blocks, laundry strung between balconies, low angle"),
        S("1.5-5s","Ground-floor shops","Street level","Tracking","Morning","Crossfade","ground-floor Roman shops opening in the morning beneath apartment windows, bread and pottery on counters"),
        S("5-15s","Fire in an insula","Wide at night","Slow push","Firelight","Match cut","a Roman apartment block on fire at night, people fleeing into the street, orange firelight"),
        S("15-21s","Top-floor window view","From inside, looking out","Pull back","Soft evening","Cut to frame 1","view from a cramped top-floor Roman apartment window over tiled rooftops at evening")],
 sound="Busy street chatter, cart wheels; crackle of fire under the collapse line; a wry pluck on 'budget option'.",
 title="Ancient Rome Had Apartment Blocks - and a Height Limit",
 desc="Most Romans lived in apartment blocks called insulae. Augustus capped them at 70 Roman feet, and the top floors were the cheapest. Older Than You Think #2.",
 tags=["history","rome","ancientrome"],
 comment="Top floor or ground floor - where would you live in Rome?",
 cta="#3: the first recorded workers' strike in history. Guess what it was about.",
 loop="The rooftop view from the top floor cuts back to the street looking up at that window.",
 length="~21s", exp="Rome + modern life (the channel's formula) with a twist ending", metric="Viewed vs swiped"),

dict(day=2, n=3, cat="Egypt / work", hooktype="'The first ever' with a relatable cause",
 topic="The first recorded strike",
 claim="Around 1157 BC, in the reign of Ramesses III, the royal tomb builders of Deir el-Medina stopped work and staged sit-ins at mortuary temples because their grain rations were late; the events were recorded on the Turin Strike Papyrus.",
 sources=[("World History Encyclopedia: The First Labor Strike in History","https://www.worldhistory.org/article/1089/the-first-labor-strike-in-history/"),
          ("Turin Strike Papyrus - overview with references","https://en.wikipedia.org/wiki/Turin_Strike_Papyrus")],
 frame="Egyptian workers sitting in protest on the steps of a temple at dusk, tools laid down in front of them. Text: THE FIRST STRIKE.",
 hook="The first recorded strike in history was over late pay.",
 script=[("0.0-1.8","History's first recorded strike was over late pay."),
         ("1.8-5.0","Egypt, around 1157 BC. The men who carved the royal tombs hadn't received their grain."),
         ("5.0-15.0","Grain was their wages. So they put down their tools and sat outside the temples until they were paid. A scribe wrote it all down."),
         ("15.0-20.0","They got their rations - eventually. Three thousand years later, same argument.")],
 osd=[("0.0-1.8","THE FIRST\nSTRIKE"),("1.8-5.0","Egypt, ~1157 BC"),("5.0-10.0","wages = grain"),("10.0-15.0","tools down, sit-in"),("15.0-20.0","same argument")],
 shots=[S("0-1.8s","Workers sitting in protest","Group on temple steps","Slow push","Dusk, warm stone","Hard cut","ancient Egyptian tomb workers sitting in protest on temple steps at dusk, tools laid on the ground in front of them"),
        S("1.8-5s","Tomb corridor","Torch-lit painted corridor","Slow dolly","Torchlight","Crossfade","a torch-lit royal tomb corridor in the Valley of the Kings with half-finished wall paintings and chisels"),
        S("5-15s","Empty grain store","Granary with empty baskets","Static","Hard sun","Match cut","an ancient Egyptian granary with empty woven baskets and scattered grain, hard sunlight"),
        S("15-20s","Scribe writing on papyrus","Hands and reed pen","Slow push","Lamplight","Cut to frame 1","an Egyptian scribe's hands writing hieratic script on papyrus with a reed pen, oil lamp light")],
 sound="Hammer-and-chisel rhythm that stops abruptly at 'put down their tools'. Silence, then crowd murmur.",
 title="The First Recorded Strike Was in Ancient Egypt, Over Late Pay",
 desc="Around 1157 BC, Egypt's royal tomb builders walked out because their grain wages were late. Older Than You Think #3.",
 tags=["history","egypt","ancientegypt"],
 comment="What would make you walk off the job?",
 cta="#4: Rome had a 7,000-man fire brigade 2,000 years ago.",
 loop="The scribe's record cuts back to the men it describes.",
 length="~20s", exp="Relatable work/money angle (US audience)", metric="Comments per 1,000 views"),

dict(day=2, n=4, cat="Rome", hooktype="Modern institution, ancient date",
 topic="The Roman vigiles: firefighters and night watch",
 claim="In AD 6 Augustus created the vigiles, about 7,000 men (largely freedmen) in seven cohorts, each covering two of Rome's fourteen districts, who fought fires and patrolled at night.",
 sources=[("Britannica: vigiles","https://www.britannica.com/topic/vigiles"),
          ("Vigiles - overview with references","https://en.wikipedia.org/wiki/Vigiles")],
 frame="Roman men in tunics passing leather buckets hand to hand toward a burning building at night. Text: ROME'S FIRE DEPARTMENT.",
 hook="Two thousand years ago, Rome had a fire department.",
 script=[("0.0-1.8","Two thousand years ago, Rome had a fire department."),
         ("1.8-5.0","After years of fires, Augustus created it in AD 6: the vigiles."),
         ("5.0-15.0","About seven thousand men in seven units, each covering two districts. They patrolled at night with buckets, axes and pumps, and dealt with burglars too."),
         ("15.0-20.0","Firefighters and night police in one job. In the year 6.")],
 osd=[("0.0-1.8","ROME'S FIRE\nDEPARTMENT"),("1.8-5.0","AD 6: the vigiles"),("5.0-10.0","~7,000 men"),("10.0-15.0","buckets, axes, pumps"),("15.0-20.0","year 6")],
 shots=[S("0-1.8s","Bucket chain at a fire","Line of men toward flames","Slow push","Firelight at night","Hard cut","ancient Roman firefighters in tunics passing leather buckets hand to hand toward a burning building at night"),
        S("1.8-5s","Augustus statue","Marble, low angle","Slow tilt","Hard daylight","Crossfade","a marble statue of Emperor Augustus against a blue sky, low angle"),
        S("5-15s","Night patrol","Men with torches in a street","Tracking","Torchlight","Match cut","a patrol of Roman watchmen with torches and axes walking a dark cobbled street"),
        S("15-20s","Smoke over rooftops at dawn","Wide city","Slow pan","Dawn haze","Cut to frame 1","smoke rising over ancient Rome's rooftops at dawn after a fire")],
 sound="Crackle and roar, shouted orders in the distance, water splashes on the beat.",
 title="Rome Had a 7,000-Man Fire Brigade 2,000 Years Ago",
 desc="In AD 6, Augustus created the vigiles: about 7,000 firefighters and night watchmen. Older Than You Think #4. Source: Britannica.",
 tags=["history","rome","ancientrome"],
 comment="Which Roman job would you have wanted?",
 cta="#5: a clay tablet with math Pythagoras got credit for - 1,000 years before him.",
 loop="Smoke over the rooftops cuts back to the fire it came from.",
 length="~20s", exp="Second Rome Short on Day 2 - does Rome win twice?", metric="Subscribers per 1,000 views"),

dict(day=3, n=5, cat="Mesopotamia / math", hooktype="Credit stolen / earlier than the famous name",
 topic="Plimpton 322",
 claim="Plimpton 322, a Babylonian clay tablet from about 1800 BC, lists values derived from Pythagorean triples - sets of whole numbers that fit a squared plus b squared equals c squared, such as 119, 120 and 169 - over a thousand years before Pythagoras.",
 sources=[("UNSW Sydney: Mathematical mystery of ancient Babylonian clay tablet solved (2017)","https://newsroom.unsw.edu.au/news/science-tech/mathematical-mystery-ancient-babylonian-clay-tablet-solved"),
          ("Plimpton 322 - overview with references","https://en.wikipedia.org/wiki/Plimpton_322")],
 note="The tablet shows they knew the relationship and could generate triples; it contains no proof. What it was for (trigonometry table vs teaching aid) is debated - don't claim a purpose.",
 frame="A cracked clay tablet covered in rows of cuneiform numbers, a right-angled triangle faintly traced in light across it. Text: 1,000 YEARS BEFORE PYTHAGORAS.",
 hook="This tablet knew Pythagoras' math a thousand years before he was born.",
 script=[("0.0-2.0","This tablet knew Pythagoras' math a thousand years before he was born."),
         ("2.0-5.0","Plimpton 322, a Babylonian clay tablet from about 1800 BC."),
         ("5.0-15.0","Its rows come from whole numbers that fit a squared plus b squared equals c squared. One of them: 119, 120 and 169. Pythagoras lived around 500 BC."),
         ("15.0-20.0","He got the name. The Babylonians had the numbers first.")],
 osd=[("0.0-2.0","1,000 YEARS\nBEFORE PYTHAGORAS"),("2.0-5.0","Plimpton 322, ~1800 BC"),("5.0-10.0","a² + b² = c²"),("10.0-15.0","119, 120, 169"),("15.0-20.0","numbers first")],
 shots=[S("0-2s","Clay tablet with triangle","Tablet fills frame","Slow push","Raking light","Hard cut","a cracked ancient Babylonian clay tablet covered in neat rows of cuneiform numbers, raking side light"),
        S("2-5s","Babylonian scribe school","Scribes at clay","Slow dolly","Warm lamplight","Crossfade","Babylonian scribes pressing a stylus into wet clay tablets in a mud-brick room, warm lamplight"),
        S("5-15s","Triangle drawn in sand","Top-down","Static","Low sun","Match cut","a right-angled triangle drawn with a stick in fine sand, long shadows at sunset"),
        S("15-20s","Greek marble bust in shadow","Bust half-lit","Slow pull back","Chiaroscuro","Cut to frame 1","a Greek marble bust of a bearded philosopher half in shadow")],
 sound="Stylus-on-clay taps as percussion. Bright bell on each number.",
 title="Babylonians Wrote Pythagorean Triples 1,000 Years Before Pythagoras",
 desc="Plimpton 322, a Babylonian tablet from about 1800 BC, is built on numbers like 119, 120 and 169. Older Than You Think #5.",
 tags=["history","math","mesopotamia"],
 comment="Who else got famous for something someone did first?",
 cta="#6: the oldest known customer complaint. It's over 3,700 years old.",
 loop="The bust returns to the tablet that beat him to it.",
 length="~20s", exp="'Credit stolen' framing - does injustice drive comments?", metric="Comments per 1,000 views"),

dict(day=3, n=6, cat="Mesopotamia / everyday life", hooktype="Modern annoyance, ancient date",
 topic="The complaint tablet to Ea-nasir",
 claim="A clay tablet from Ur, dated to about 1750 BC and now in the British Museum, records a customer named Nanni complaining to the merchant Ea-nasir that he had been sold substandard copper ingots and that his messenger had been treated with contempt.",
 sources=[("Complaint tablet to Ea-nasir - overview with references","https://en.wikipedia.org/wiki/Complaint_tablet_to_Ea-nasir"),
          ("A. Leo Oppenheim, Letters from Mesopotamia (1967) - standard translation",None)],
 frame="A small palm-sized clay tablet with dense cuneiform in a museum case, a copper ingot beside it. Text: 1ST CUSTOMER COMPLAINT.",
 hook="The oldest known customer complaint is written in clay.",
 script=[("0.0-1.8","The oldest known customer complaint is written in clay."),
         ("1.8-5.0","Ur, around 1750 BC. Nanni paid a merchant, Ea-nasir, for copper."),
         ("5.0-15.0","The copper was bad, and his servant was sent away empty-handed. So Nanni pressed it into clay: who did Ea-nasir think he was, treating him with such contempt?"),
         ("15.0-20.0","It's in the British Museum. Ea-nasir is still famous for bad service.")],
 osd=[("0.0-1.8","1ST CUSTOMER\nCOMPLAINT"),("1.8-5.0","Ur, ~1750 BC"),("5.0-10.0","bad copper"),("10.0-15.0","servant sent away"),("15.0-20.0","British Museum")],
 shots=[S("0-1.8s","Tablet in museum case","Tablet + copper ingot","Slow push","Museum spot","Hard cut","a small ancient clay tablet with dense cuneiform displayed in a museum case beside a dull copper ingot"),
        S("1.8-5s","Ur market","Stalls, mud brick","Tracking","Harsh sun","Crossfade","a bustling market in the ancient city of Ur with copper ingots on a merchant's stall, mud-brick walls, harsh sun"),
        S("5-15s","Angry hands pressing clay","Hands and stylus","Close, handheld","Lamplight","Match cut","hands pressing a reed stylus hard into a wet clay tablet by oil lamp light"),
        S("15-20s","Museum gallery","Visitors from behind","Slow pull back","Soft gallery","Cut to frame 1","visitors seen from behind in a quiet museum gallery of Mesopotamian artefacts")],
 sound="Market bustle; the stylus scratches grow harder and faster through the complaint. A comic beat of silence before 'bad service'.",
 title="The Oldest Known Customer Complaint Is Over 3,700 Years Old",
 desc="Around 1750 BC, a man named Nanni complained in clay that the merchant Ea-nasir sold him bad copper. Older Than You Think #6.",
 tags=["history","mesopotamia","funny"],
 comment="Write your one-star review for Ea-nasir.",
 cta="#7: someone built a steam-powered machine in the first century AD.",
 loop="Museum visitors return to the tablet in its case.",
 length="~20s", exp="Humour + a role-play comment trigger ('write the review')", metric="Comments per 1,000 views"),

dict(day=4, n=7, cat="Roman Egypt / technology", hooktype="Invention 'too early'",
 topic="Hero of Alexandria's aeolipile",
 claim="In the 1st century AD, Hero of Alexandria described the aeolipile: a sphere on an axle over a sealed boiler that spun as steam escaped through two bent nozzles. It was treated as a curiosity and never put to practical work.",
 sources=[("Britannica: Heron of Alexandria","https://www.britannica.com/biography/Heron-of-Alexandria"),
          ("Aeolipile - overview with references","https://en.wikipedia.org/wiki/Aeolipile")],
 note="Why it wasn't used is a historians' debate (cheap and enslaved labour is one theory). The script labels it as one theory.",
 frame="A bronze sphere spinning over a small fire, jets of steam curling from two bent nozzles, in a stone workshop. Text: STEAM POWER, 1ST CENTURY.",
 hook="Someone built a steam-powered machine in the first century.",
 script=[("0.0-1.8","Someone built a steam-powered machine in the first century."),
         ("1.8-5.0","Hero of Alexandria, Roman Egypt. Water boiled under a metal ball on an axle."),
         ("5.0-15.0","Steam shot from two bent nozzles and the ball spun. Then nobody put it to work. One theory: with so much enslaved labour, nobody needed it."),
         ("15.0-20.0","The Industrial Revolution was about 1,700 years away.")],
 osd=[("0.0-1.8","STEAM POWER\n1ST CENTURY"),("1.8-5.0","Hero of Alexandria"),("5.0-10.0","steam spins the ball"),("10.0-15.0","never put to work"),("15.0-20.0","1,700 years early")],
 shots=[S("0-1.8s","Spinning aeolipile","Sphere centered","Slow orbit","Firelight + steam","Hard cut","a polished bronze aeolipile sphere spinning over a small fire, jets of steam curling from two bent nozzles, stone workshop"),
        S("1.8-5s","Alexandria harbour","Wide, lighthouse","Slow pan","Morning haze","Crossfade","ancient Alexandria harbour with the great lighthouse in morning haze, ships at anchor"),
        S("5-15s","Scroll with a diagram","Hands unrolling papyrus","Slow push","Lamplight","Match cut","hands unrolling a papyrus scroll with a hand-drawn diagram of a steam device, lamp light"),
        S("15-20s","Steam locomotive silhouette","Engine in fog","Slow push","Grey dawn","Cut to frame 1","an early 19th century steam locomotive silhouetted in fog at dawn")],
 sound="Hiss and whirr of steam building to a spin; a train whistle faintly on 'Industrial Revolution'.",
 title="Roman Egypt Had a Steam-Powered Machine 1,700 Years Early",
 desc="Hero of Alexandria described a steam-spun sphere in the 1st century AD - and nobody put it to work. Older Than You Think #7. Source: Britannica.",
 tags=["history","inventions","technology"],
 comment="If they'd used it, what would the world look like now?",
 cta="#8: Rome had a state courier network across its empire. You just weren't allowed to use it.",
 loop="The locomotive's steam dissolves into the aeolipile's steam.",
 length="~20s", exp="'What if' comment trigger", metric="Comments per 1,000 views"),

dict(day=4, n=8, cat="Rome", hooktype="Modern service, ancient catch",
 topic="The cursus publicus",
 claim="Augustus established the cursus publicus, a state courier and transport service with stations along Roman roads for changing animals and resting; it carried officials, official messages and state goods, and use required a government permit.",
 sources=[("Britannica: cursus publicus","https://www.britannica.com/topic/cursus-publicus"),
          ("Cursus publicus - overview with references","https://en.wikipedia.org/wiki/Cursus_publicus")],
 frame="A Roman rider on a paved road at speed, a relay station with fresh horses ahead, milestone in the foreground. Text: ROMAN EXPRESS DELIVERY.",
 hook="Rome had express delivery. You just weren't allowed to use it.",
 script=[("0.0-2.0","Rome had express delivery. You just weren't allowed to use it."),
         ("2.0-5.0","Augustus set it up: the cursus publicus, the state courier service."),
         ("5.0-15.0","Along Roman roads, stations had fresh animals and beds for couriers. Officials, orders and state goods crossed the empire. But you needed a government pass."),
         ("15.0-20.0","Your own letters? Hand them to a friend who's travelling.")],
 osd=[("0.0-2.0","ROMAN EXPRESS\nDELIVERY"),("2.0-5.0","cursus publicus"),("5.0-10.0","relay stations"),("10.0-15.0","state only - pass required"),("15.0-20.0","ask a friend")],
 shots=[S("0-2s","Rider on a Roman road","Rider approaching camera","Tracking","Golden hour dust","Hard cut","a Roman courier on horseback galloping along a straight paved Roman road, a relay station with fresh horses ahead, a milestone in the foreground"),
        S("2-5s","Map of roads","Stone relief map feel","Slow push","Warm","Crossfade","a bronze relief map of the Roman road network across Europe, warm light"),
        S("5-15s","Relay station","Stable yard, horse swap","Handheld","Dawn","Match cut","a Roman roadside relay station at dawn, stablehands leading fresh horses to a waiting courier"),
        S("15-20s","Wax tablet letter handed over","Hands exchanging","Static","Soft","Cut to frame 1","two hands passing a sealed wax tablet letter between travellers on a road")],
 sound="Galloping hooves as the tempo. A stamp/seal thud on 'government pass'.",
 title="Rome Had Express Delivery - Only the State Could Use It",
 desc="Augustus's cursus publicus ran relay stations along Roman roads - for officials only. Older Than You Think #8. Source: Britannica.",
 tags=["history","rome","ancientrome"],
 comment="How long do you think a letter took from Rome to Britain?",
 cta="#9: medieval people did NOT think the Earth was flat. Here's who started that myth.",
 loop="The letter handed over rides off down the same road.",
 length="~20s", exp="'Catch' twist in the hook", metric="Viewed vs swiped"),

dict(day=5, n=9, cat="Myth-busting", hooktype="Correcting something taught in school",
 topic="Medieval people knew the Earth was round",
 claim="Educated medieval Europeans knew the Earth was a sphere (Bede in the 700s; Sacrobosco's 'On the Sphere' was a standard university text from the 1200s). Columbus's critics objected that he underestimated the Earth's size - correctly. The flat-Earth story was popularised in the 1800s, notably by Washington Irving's 1828 biography of Columbus.",
 sources=[("Myth of the flat Earth - overview with references","https://en.wikipedia.org/wiki/Myth_of_the_flat_Earth"),
          ("Jeffrey Burton Russell, Inventing the Flat Earth (1991)",None)],
 frame="A medieval illuminated manuscript page showing a round, spherical Earth, a monk's hand pointing at it. Text: THEY KNEW.",
 hook="Medieval people knew the Earth was round.",
 script=[("0.0-1.5","Medieval people knew the Earth was round."),
         ("1.5-5.0","Scholars wrote about a round Earth in the 700s. By the 1200s, students used a textbook called On the Sphere."),
         ("5.0-15.0","Columbus's critics didn't fear the edge. They said he'd underestimated the world's size. They were right."),
         ("15.0-20.0","The flat-Earth story? Spread in 1828 by Washington Irving, who wrote The Legend of Sleepy Hollow.")],
 osd=[("0.0-1.5","THEY KNEW"),("1.5-5.0","'On the Sphere', 1200s"),("5.0-10.0","critics: 'too far'"),("10.0-15.0","they were right"),("15.0-20.0","myth: 1828")],
 shots=[S("0-1.5s","Manuscript with a round Earth","Page fills frame","Slow push","Candlelight","Hard cut","a medieval illuminated manuscript page with a painted spherical Earth and gold leaf, a hand pointing at it, candlelight"),
        S("1.5-5s","Medieval classroom","Students from behind","Slow dolly","Window light","Crossfade","a medieval university lecture hall, students seen from behind listening to a master with an armillary sphere, window light"),
        S("5-15s","Ships at sea","Three ships on open ocean","Aerial push","Stormy light","Match cut","three 15th century caravels on a vast open ocean under dramatic clouds, aerial view"),
        S("15-20s","19th-century writer's desk","Quill and book","Static","Gaslight","Cut to frame 1","a 19th century writing desk with a quill and an open leather-bound book by gaslight")],
 sound="Gregorian-style choir pad (original, not a recording) into ocean swell; a quill scratch on '1828'.",
 title="Medieval People Knew the Earth Was Round. The Myth Came in the 1800s.",
 desc="Medieval scholars taught a round Earth. The flat-Earth story was popularised in 1828 by Washington Irving. Older Than You Think #9.",
 tags=["history","myths","medieval"],
 comment="What 'fact' from school turned out to be wrong?",
 cta="#10: a 3,800-year-old hymn that's also a beer recipe.",
 loop="Irving's desk cuts back to the manuscript that proves him wrong.",
 length="~21s", exp="'School lied to you' myth-busting", metric="Shares per 1,000 views"),

dict(day=5, n=10, cat="Mesopotamia / food", hooktype="Double identity",
 topic="The Hymn to Ninkasi",
 claim="The Sumerian Hymn to Ninkasi, recorded around 1800 BC, praises the goddess of beer and describes brewing steps; in 1989 Anchor Brewing in San Francisco, working with Solomon Katz, brewed a beer based on it.",
 sources=[("Ninkasi - overview with references","https://en.wikipedia.org/wiki/Ninkasi"),
          ("Katz & Maytag 1991, 'Brewing an Ancient Beer', Archaeology 44(4)",None)],
 frame="A clay tablet beside a clay jar of foaming beer with long reed straws, in warm lamplight. Text: A HYMN + A RECIPE.",
 hook="This 3,800-year-old hymn is also a beer recipe.",
 script=[("0.0-1.8","This 3,800-year-old hymn is also a beer recipe."),
         ("1.8-5.0","It's a Sumerian song to Ninkasi, the goddess of beer, from around 1800 BC."),
         ("5.0-15.0","It walks through the steps: baking the bread, soaking the malt, mixing the vat, pouring the beer. Singing it may have helped brewers remember."),
         ("15.0-20.0","In 1989, a San Francisco brewery followed it and made the beer.")],
 osd=[("0.0-1.8","A HYMN\n+ A RECIPE"),("1.8-5.0","Ninkasi, ~1800 BC"),("5.0-10.0","bread, malt, vat"),("10.0-15.0","sung to remember"),("15.0-20.0","brewed again: 1989")],
 shots=[S("0-1.8s","Tablet and beer jar","Tablet + jar with straws","Slow push","Warm lamplight","Hard cut","an ancient clay tablet beside a clay jar of foaming beer with long reed drinking straws, warm lamplight"),
        S("1.8-5s","Temple brewery","Women brewing in a courtyard","Slow dolly","Morning sun","Crossfade","ancient Sumerian brewers stirring large clay vats in a sunlit temple courtyard"),
        S("5-15s","Bread soaking in water","Close on vat","Top-down","Soft","Match cut","loaves of barley bread crumbling into a clay vat of water and malt, top-down"),
        S("15-20s","Modern brewery tanks","Copper kettles","Slow pan","Industrial warm","Cut to frame 1","gleaming copper brewing kettles in a brewery, warm industrial light")],
 sound="Simple lyre-like plucked melody (original composition) with a hand drum; a pour and fizz on 'pouring out the beer'.",
 title="This 3,800-Year-Old Hymn Is Also a Beer Recipe",
 desc="The Sumerian Hymn to Ninkasi (around 1800 BC) describes how to brew beer. A San Francisco brewery made it in 1989. Older Than You Think #10.",
 tags=["history","beer","mesopotamia"],
 comment="What recipe from your family should be turned into a song?",
 cta="#11: China printed government paper money over 600 years before Europe.",
 loop="Modern kettles cut back to the clay jar - same drink, 3,800 years apart.",
 length="~20s", exp="Food/drink category", metric="Shares per 1,000 views"),

dict(day=6, n=11, cat="Money", hooktype="Date gap between two famous firsts",
 topic="The jiaozi: government paper money in 1024",
 claim="In Sichuan, where heavy iron coins were used, merchants traded paper certificates; in 1024 the Song government took over issuing them (the jiaozi), the first government-issued paper money. Europe's first banknotes were issued by Stockholms Banco in 1661.",
 sources=[("Jiaozi (currency) - overview with references","https://en.wikipedia.org/wiki/Jiaozi_(currency)"),
          ("Stockholms Banco - overview with references","https://en.wikipedia.org/wiki/Stockholms_Banco")],
 frame="A stack of heavy iron coins on strings beside a single printed paper note with red seals. Text: 637 YEARS EARLIER.",
 hook="China had government paper money over 600 years before Europe.",
 script=[("0.0-1.8","China had government paper money over 600 years before Europe."),
         ("1.8-5.0","Sichuan, 11th century. Iron coins were so heavy that merchants traded paper receipts instead."),
         ("5.0-15.0","In 1024, the Song government took over and printed the jiaozi, the first government paper money. Europe's first banknotes? Stockholm, 1661."),
         ("15.0-20.0","And it all started because coins were too heavy to carry.")],
 osd=[("0.0-1.8","637 YEARS\nEARLIER"),("1.8-5.0","iron coins = heavy"),("5.0-10.0","1024: the jiaozi"),("10.0-15.0","Europe: 1661"),("15.0-20.0","too heavy to carry")],
 shots=[S("0-1.8s","Iron coins vs paper note","Coins left, note right","Slow push","Warm side light","Hard cut","a heavy stack of iron cash coins strung on cords beside a single printed paper banknote with red seals, warm side light"),
        S("1.8-5s","Merchant with heavy strings of coins","Merchant from behind","Tracking","Market daylight","Crossfade","a Song dynasty merchant seen from behind carrying heavy strings of iron coins through a busy market street"),
        S("5-15s","Printing blocks","Carved wooden block, ink","Slow push","Workshop light","Match cut","a carved wooden printing block being inked and pressed onto paper in a Song dynasty workshop"),
        S("15-20s","17th-century Stockholm bank counter","Counter, quill","Static","Candlelight","Cut to frame 1","a 17th century Swedish bank counter with a quill, ledger and paper notes, candlelight")],
 sound="Heavy metallic clinks at the start that give way to the light rustle of paper.",
 title="China Printed Government Paper Money 637 Years Before Europe",
 desc="The Song government issued the jiaozi in 1024. Europe's first banknotes came in 1661. Older Than You Think #11.",
 tags=["history","money","china"],
 comment="Would you have trusted paper if you'd only ever used coins?",
 cta="#12: the oldest recorded joke. It's nearly 4,000 years old - and it's rude.",
 loop="The Stockholm note cuts back to the Chinese one 637 years earlier.",
 length="~20s", exp="Money category (high-value audience) with a numeric gap in the title", metric="Viewed vs swiped"),

dict(day=6, n=12, cat="Everyday life / humour", hooktype="Humour + 'oldest ever'",
 topic="The oldest recorded joke",
 claim="A Sumerian proverb from about 1900 BC was identified in a 2008 University of Wolverhampton survey as the oldest recorded joke: roughly, something that has never happened since time immemorial - a young woman did not fart in her husband's lap.",
 sources=[("Reuters / Guinness-reported University of Wolverhampton study, 2008 (led by Paul McDonald)",None),
          ("Sumerian proverb collections, ETCSL (Oxford) - source texts","https://etcsl.orinst.ox.ac.uk/")],
 note="Translations vary; say 'roughly' and don't quote it as exact.",
 frame="A small Sumerian clay tablet with a single highlighted line of cuneiform, and a laughing-crowd silhouette in warm light behind. Text: THE OLDEST JOKE.",
 hook="The oldest joke ever recorded is a fart joke.",
 script=[("0.0-1.5","The oldest joke ever recorded is a fart joke."),
         ("1.5-5.0","Sumerian, around 1900 BC. Researchers ranked it oldest in 2008."),
         ("5.0-15.0","Roughly: something that has never happened since the beginning of time - a young woman who didn't fart in her husband's lap. We don't fully get it."),
         ("15.0-20.0","Nearly 4,000 years. Humans have always been this childish.")],
 osd=[("0.0-1.5","THE OLDEST\nJOKE"),("1.5-5.0","Sumer, ~1900 BC"),("5.0-11.0","'never happened since\nthe beginning of time...'"),("11.0-15.0","set-up + punchline"),("15.0-20.0","always this childish")],
 shots=[S("0-1.5s","Tablet with highlighted line","Tablet close","Slow push","Warm spot","Hard cut","a small Sumerian clay tablet with one line of cuneiform catching warm light, silhouettes of people laughing softly blurred behind"),
        S("1.5-5s","Sumerian city at dusk","Ziggurat, wide","Slow pan","Dusk","Crossfade","the Sumerian city of Ur at dusk with its ziggurat, lamps being lit"),
        S("5-15s","People laughing around a fire","Silhouettes, no faces","Static","Firelight","Match cut","silhouettes of ancient Mesopotamian villagers laughing around an evening fire"),
        S("15-20s","Tablet in a museum","Museum case","Slow pull back","Soft","Cut to frame 1","a Sumerian clay tablet in a quiet museum case")],
 sound="A single comic horn note is too much - use a dry pause before the punchline and a soft crowd chuckle after.",
 title="The Oldest Recorded Joke Is Nearly 4,000 Years Old - and It's a Fart Joke",
 desc="A Sumerian joke from about 1900 BC was ranked the oldest recorded joke in 2008. Older Than You Think #12.",
 tags=["history","funny","ancient"],
 comment="Tell us the oldest joke you know.",
 cta="#13: the oldest song with written music. You can still hear it played.",
 loop="The museum tablet cuts back to the same tablet up close.",
 length="~20s", exp="Pure humour - does it out-share the awe Shorts?", metric="Shares per 1,000 views"),

dict(day=7, n=13, cat="Music", hooktype="'Oldest you can still hear'",
 topic="Hurrian Hymn No. 6",
 claim="Clay tablets from Ugarit (in modern Syria), about 1400 BC, preserve a hymn to the goddess Nikkal with instructions for the lyre - the oldest substantially complete notated melody known. Scholars disagree on how to read the notation, so reconstructions differ.",
 sources=[("Hurrian songs - overview with references","https://en.wikipedia.org/wiki/Hurrian_songs")],
 note="Do NOT use a recorded modern performance - those are copyrighted. Use an original lyre-style melody.",
 frame="A broken clay tablet with cuneiform lines, a lyre resting beside it in lamplight. Text: THE OLDEST SONG.",
 hook="This is the oldest song we can still play.",
 script=[("0.0-1.5","This is the oldest song we can still play."),
         ("1.5-5.0","Pressed into clay in Ugarit, modern Syria, around 1400 BC."),
         ("5.0-15.0","A hymn to Nikkal, goddess of orchards, with instructions for the lyre. The oldest largely complete written melody ever found. Scholars read it differently, so every version sounds different."),
         ("15.0-20.0","3,400 years later, musicians still perform it.")],
 osd=[("0.0-1.5","THE OLDEST\nSONG"),("1.5-5.0","Ugarit, ~1400 BC"),("5.0-10.0","written for the lyre"),("10.0-15.0","every version differs"),("15.0-20.0","3,400 years")],
 shots=[S("0-1.5s","Tablet and lyre","Tablet foreground, lyre behind","Slow push","Lamplight","Hard cut","a broken clay tablet inscribed with cuneiform beside an ancient wooden lyre, oil lamp light"),
        S("1.5-5s","Ugarit harbour city","Wide, coast","Slow aerial","Mediterranean sun","Crossfade","the ancient harbour city of Ugarit on the Syrian coast, stone buildings and ships, bright Mediterranean sun"),
        S("5-15s","Hands plucking a lyre","Hands only","Static","Warm","Match cut","hands plucking the strings of an ancient lyre in warm light, strings vibrating"),
        S("15-20s","Orchard at dusk","Trees, wide","Slow push","Dusk","Cut to frame 1","an ancient fruit orchard at dusk, warm low light through the trees")],
 sound="An original, simple lyre melody underneath the whole Short (not a copyrighted recording).",
 title="The Oldest Song With Written Music Is About 3,400 Years Old",
 desc="A hymn from Ugarit, around 1400 BC, is the oldest largely complete written melody known. Older Than You Think #13.",
 tags=["history","music","ancient"],
 comment="Which song from today should people still hear in 3,400 years?",
 cta="#14: the Aztecs made school mandatory - long before most of Europe.",
 loop="The lyre melody resolves and restarts with the first frame.",
 length="~20s", exp="Audio-led Short (the melody is the hook)", metric="Average percentage viewed"),

dict(day=7, n=14, cat="Americas / education", hooktype="'Before Europe' comparison",
 topic="Compulsory schooling in the Aztec Empire",
 claim="In the Aztec Empire (15th-early 16th century), schooling was compulsory: children of nobles attended the calmecac, and commoners' children the telpochcalli ('house of youth'), found in each neighbourhood (calpulli). Most European states made schooling compulsory only in the 18th-19th centuries.",
 sources=[("Telpochcalli - overview with references","https://en.wikipedia.org/wiki/Telpochcalli"),
          ("Calmecac - overview with references","https://en.wikipedia.org/wiki/Calmecac"),
          ("Codex Mendoza (16th c.), Bodleian Library - primary source on Aztec education",None)],
 note="Most detail comes from 16th-century Spanish-era sources; what girls' schooling looked like varies by account. Say 'children', not 'every boy and girl'.",
 frame="Aztec children seen from behind walking into a stone school building in a busy neighbourhood of Tenochtitlan, lake and temples beyond. Text: SCHOOL WAS MANDATORY.",
 hook="The Aztecs made school mandatory.",
 script=[("0.0-1.5","The Aztecs made school mandatory."),
         ("1.5-5.0","In the 1400s, children in the Aztec Empire had to go to school. Not just the rich."),
         ("5.0-15.0","Nobles' children went to the calmecac, to learn religion, astronomy and law. Everyone else's went to the telpochcalli, the house of youth. Every neighbourhood had one."),
         ("15.0-20.0","In most of Europe, mandatory school came centuries later.")],
 osd=[("0.0-1.5","SCHOOL WAS\nMANDATORY"),("1.5-5.0","Aztec Empire, 1400s"),("5.0-10.0","nobles: calmecac"),("10.0-15.0","everyone: telpochcalli"),("15.0-20.0","Europe: centuries later")],
 shots=[S("0-1.5s","Children walking to school","From behind, stone building","Tracking","Morning sun","Hard cut","Aztec children seen from behind walking into a stone school building in a neighbourhood of Tenochtitlan, lake and temples in the distance, morning sun"),
        S("1.5-5s","Tenochtitlan from above","Aerial, causeways","Slow aerial","Clear morning","Crossfade","aerial view of Tenochtitlan on its lake with causeways, canals and the great temple, clear morning"),
        S("5-15s","Codex painting of a lesson","Painted codex page","Slow pan","Warm","Match cut","a colourful Aztec codex page showing a teacher and pupils, warm light"),
        S("15-20s","European village schoolroom, 1800s","Empty desks","Static","Grey window light","Cut to frame 1","an empty 19th century European village schoolroom with wooden desks, grey window light")],
 sound="Conch-shell call at 0.2s, drum and flute pattern (original), a school bell on 'centuries later'.",
 title="The Aztecs Made School Mandatory Long Before Most of Europe",
 desc="In the Aztec Empire, children attended the calmecac or the telpochcalli - one in every neighbourhood. Older Than You Think #14.",
 tags=["history","aztec","education"],
 comment="Would you have survived Aztec school?",
 cta="That's the first 14. Week two starts right after: more of the past doing things we think are modern.",
 loop="The empty European schoolroom cuts back to Aztec children walking in, centuries earlier.",
 length="~20s", exp="Non-European 'firsts' - does it widen the audience?", metric="Subscribers per 1,000 views"),
]
