# -*- coding: utf-8 -*-
# History That Explains the World - "Older Than You Think" #15-24.
#
# Written 2026-09-19 because History is the one channel the numbers say is
# growing (28-day views 39,887 -> 43,611, watch hours 116 -> 140 in four days)
# and it had run down to 9 publishable scripts while the free model was taking
# minutes per request. Built on the two shapes its own winners share, measured:
#   "X is older than Y"      Oxford/Aztecs 997, sharks/trees 1,077
#   "you were taught wrong"  Romans lived longer 1,071, Ottomans until 1922 1,045
# and written to 36-60 seconds, the length its data prefers (412 median views).

V = ("vertical 9:16, photorealistic historical reconstruction, cinematic, natural "
     "period lighting, shallow depth of field, no text, no watermark")


def S(t, subj, comp, move, light, trans, prompt):
    return dict(t=t, subj=subj, comp=comp, move=move, light=light, trans=trans,
                prompt=prompt + ", " + V)


EXTRA = [
dict(day=8, n=15, cat="Engineering", hooktype="A landmark that changes size",
 topic="The Eiffel Tower grows in summer",
 claim="The Eiffel Tower is built from about 7,300 tonnes of iron, which expands in heat; its official site says the top can grow by up to around 15 cm in summer and moves slightly away from the sun as the sunlit side expands.",
 sources=[("La Tour Eiffel (official site): the Tower in figures", "https://www.toureiffel.paris/en/the-monument/key-figures"),
          ("Thermal expansion - Britannica", "https://www.britannica.com/science/thermal-expansion")],
 frame="The Eiffel Tower against a hot blue summer sky, heat shimmer at the base. Text: IT GROWS IN SUMMER.",
 hook="The Eiffel Tower grows about 15 centimeters every summer.",
 script=[("0.0-2.5", "The Eiffel Tower grows about 15 centimeters every summer."),
         ("2.5-7.0", "It's made of iron - about 7,300 tonnes of it - and iron expands when it heats up."),
         ("7.0-19.0", "On a hot day the side in the sun stretches more than the side in the shade, so the top leans very slightly away from the sun. When winter comes, the whole tower shrinks back."),
         ("19.0-23.0", "It is never quite the same height two days in a row.")],
 osd=[("0.0-2.5", "IT GROWS\nIN SUMMER"), ("2.5-7.0", "7,300 tonnes of iron"), ("7.0-13.0", "heat = expansion"),
      ("13.0-19.0", "leans away from the sun"), ("19.0-23.0", "never the same height")],
 shots=[S("0-2.5s", "Eiffel Tower in summer", "Tower fills frame", "Slow tilt up", "Hot blue sky", "Hard cut",
          "the Eiffel Tower against a hot deep blue summer sky, heat shimmer at the base, bright sunlight"),
        S("2.5-7s", "Iron lattice close", "Rivets and beams", "Slow push", "Hard sun", "Crossfade",
          "close up of the Eiffel Tower's riveted iron lattice beams in hard sunlight"),
        S("7-19s", "Tower at sunset", "Tower and sun", "Slow drift", "Golden hour", "Match cut",
          "the Eiffel Tower at golden hour with the low sun beside it"),
        S("19-23s", "Tower in winter", "Snowy Champ de Mars", "Static", "Cold grey", "Cut to frame 1",
          "the Eiffel Tower in winter with snow on the Champ de Mars, cold grey light")],
 sound="Warm summer ambience, a low metallic creak on 'stretches'.",
 title="The Eiffel Tower Grows About 15 Centimeters Every Summer",
 desc="About 7,300 tonnes of iron expand in the heat - the Eiffel Tower is taller in summer. Older Than You Think #15. Source: La Tour Eiffel.",
 tags=["history", "engineering", "paris"],
 comment="What's the hottest place you've ever been?",
 cta="#16: the fax machine is older than the telephone.",
 loop="Winter tower cuts back to the summer tower.",
 length="~27s", exp="Landmark with a physical surprise", metric="Shares per 1,000 views"),

dict(day=8, n=16, cat="Inventions", hooktype="'Older than' between two inventions",
 topic="The fax machine is older than the telephone",
 claim="Scottish clockmaker Alexander Bain patented an electric printing telegraph that could transmit images - the principle of the fax - in 1843. Alexander Graham Bell's telephone patent was granted in 1876.",
 sources=[("Britannica: fax", "https://www.britannica.com/technology/fax"),
          ("Britannica: Alexander Graham Bell", "https://www.britannica.com/biography/Alexander-Graham-Bell")],
 frame="A brass-and-wood Victorian telegraph apparatus with pendulums, a strip of paper printing a picture. Text: OLDER THAN THE PHONE.",
 hook="The fax machine is older than the telephone.",
 script=[("0.0-2.5", "The fax machine is older than the telephone."),
         ("2.5-8.0", "In 1843, a Scottish clockmaker named Alexander Bain patented a way to send images down a telegraph wire."),
         ("8.0-20.0", "Two synchronised pendulums scanned a picture line by line at each end. Alexander Graham Bell's telephone patent came thirty-three years later, in 1876."),
         ("20.0-24.0", "People could send a picture before they could make a call.")],
 osd=[("0.0-2.5", "OLDER THAN\nTHE PHONE"), ("2.5-8.0", "fax idea: 1843"), ("8.0-14.0", "pendulums scan the image"),
      ("14.0-20.0", "telephone: 1876"), ("20.0-24.0", "picture before a call")],
 shots=[S("0-2.5s", "Victorian telegraph with pendulums", "Machine fills frame", "Slow push", "Warm workshop light", "Hard cut",
          "a brass and wood Victorian telegraph apparatus with two swinging pendulums printing a picture onto a strip of paper, warm workshop light"),
        S("2.5-8s", "Clockmaker's bench", "Hands and gears", "Slow dolly", "Lamplight", "Crossfade",
          "a Victorian clockmaker's hands assembling brass gears and a pendulum on a wooden workbench, lamplight"),
        S("8-20s", "Telegraph wires", "Poles across a field", "Tracking", "Overcast 1840s", "Match cut",
          "telegraph poles and wires running across a green English field in the 1840s"),
        S("20-24s", "Early telephone", "Wooden telephone close", "Static", "Soft window light", "Cut to frame 1",
          "an 1870s wooden telephone with a brass earpiece on a desk, soft window light")],
 sound="Ticking pendulum rhythm; a bell ring on 1876.",
 title="The Fax Machine Is Older Than the Telephone",
 desc="Alexander Bain patented the principle of the fax in 1843. Bell's telephone patent: 1876. Older Than You Think #16. Sources: Britannica.",
 tags=["history", "inventions", "technology"],
 comment="Did you ever use a fax machine?",
 cta="#17: woolly mammoths were still alive when the pyramids went up.",
 loop="The telephone cuts back to the pendulums that came first.",
 length="~27s", exp="Invention-order surprise", metric="Shares per 1,000 views"),

dict(day=9, n=17, cat="Prehistory", hooktype="Two things you never pictured together",
 topic="Woolly mammoths were alive when the Great Pyramid was built",
 claim="A population of woolly mammoths survived on Wrangel Island, off north-east Siberia, until roughly 4,000 years ago (around 2000 BC); the Great Pyramid was completed around 2560 BC.",
 sources=[("Vartanyan, Garutt & Sher 1993, Nature - Holocene dwarf mammoths from Wrangel Island", "https://www.nature.com/articles/362337a0"),
          ("Woolly mammoth - overview with references", "https://en.wikipedia.org/wiki/Woolly_mammoth")],
 frame="A woolly mammoth on a snowy island shore under a pale sky. Text: ALIVE WHEN THE PYRAMIDS ROSE.",
 hook="Woolly mammoths were still alive when the Great Pyramid was built.",
 script=[("0.0-3.0", "Woolly mammoths were still alive when the Great Pyramid was built."),
         ("3.0-7.0", "Not on the mainland. On Wrangel Island, off the coast of Siberia."),
         ("7.0-19.0", "A small population survived there until about 4,000 years ago. The Great Pyramid was finished around 2560 BC - so for centuries, the pyramid and the mammoths existed at the same time."),
         ("19.0-23.0", "The last mammoth died after the pyramids were already old.")],
 osd=[("0.0-3.0", "ALIVE WHEN THE\nPYRAMIDS ROSE"), ("3.0-7.0", "Wrangel Island"), ("7.0-13.0", "last ones: ~4,000 yrs ago"),
      ("13.0-19.0", "pyramid: ~2560 BC"), ("19.0-23.0", "the overlap")],
 shots=[S("0-3s", "Mammoth on island shore", "Mammoth mid-frame", "Slow push", "Pale arctic light", "Hard cut",
          "a woolly mammoth standing on a snowy island shore under a pale arctic sky, sharp detail on its fur"),
        S("3-7s", "Wrangel Island", "Wide tundra and sea", "Aerial", "Cold blue", "Crossfade",
          "aerial view of a remote arctic island with tundra and a grey sea"),
        S("7-19s", "Pyramid in the desert", "Wide, clean", "Slow drift", "Golden hour", "Match cut",
          "the Great Pyramid of Giza newly finished with smooth white casing stones, golden hour, wide"),
        S("19-23s", "Mammoth tusk in ice", "Close", "Slow push", "Soft", "Cut to frame 1",
          "a mammoth tusk half buried in frozen ground, soft light")],
 sound="Wind over tundra, a deep low horn on 'at the same time'.",
 title="Woolly Mammoths Were Still Alive When the Great Pyramid Was Built",
 desc="Mammoths survived on Wrangel Island until about 4,000 years ago; the Great Pyramid was finished around 2560 BC. Older Than You Think #17.",
 tags=["history", "mammoth", "ancienthistory"],
 comment="Which extinct animal would you bring back?",
 cta="#18: the lighter was invented before the match.",
 loop="The tusk in the ice cuts back to the living mammoth.",
 length="~27s", exp="Cross-domain overlap (nature + monument)", metric="Views vs channel median"),

dict(day=9, n=18, cat="Inventions", hooktype="'Older than' between two everyday objects",
 topic="The lighter came before the match",
 claim="German chemist Johann Wolfgang Döbereiner invented a self-igniting lamp in 1823, in which hydrogen ignited on contact with a platinum catalyst; John Walker, an English pharmacist, invented the friction match in 1826.",
 sources=[("Döbereiner's lamp - overview with references", "https://en.wikipedia.org/wiki/D%C3%B6bereiner%27s_lamp"),
          ("Britannica: match", "https://www.britannica.com/technology/match-ignition-device")],
 frame="A 19th-century glass-and-brass lamp with a small flame at the nozzle, a single unlit match beside it. Text: THE LIGHTER CAME FIRST.",
 hook="The lighter was invented before the match.",
 script=[("0.0-2.5", "The lighter was invented before the match."),
         ("2.5-7.0", "In 1823, a German chemist named Johann Döbereiner built a lamp that lit itself."),
         ("7.0-19.0", "Hydrogen gas flowed over platinum, and the platinum made it catch fire. Thousands were sold. The friction match - strike it, and it lights - came from an English pharmacist, John Walker, three years later."),
         ("19.0-23.0", "We had the lighter first. The match just took over.")],
 osd=[("0.0-2.5", "THE LIGHTER\nCAME FIRST"), ("2.5-7.0", "Döbereiner, 1823"), ("7.0-13.0", "hydrogen + platinum = fire"),
      ("13.0-19.0", "friction match: 1826"), ("19.0-23.0", "lighter first")],
 shots=[S("0-2.5s", "Döbereiner's lamp", "Lamp and match", "Slow push", "Warm flame light", "Hard cut",
          "a 19th century glass and brass lamp with a small flame at its brass nozzle, a single unlit wooden match lying beside it"),
        S("2.5-7s", "Chemist's laboratory", "Glassware on bench", "Slow dolly", "Candlelight", "Crossfade",
          "an 1820s chemistry laboratory with glass flasks and brass instruments on a wooden bench, candlelight"),
        S("7-19s", "Flame catching", "Macro flame", "Slow motion", "Dark with flame", "Match cut",
          "macro of a small bright flame catching at the tip of a brass nozzle"),
        S("19-23s", "Match striking", "Match close", "Slow motion", "Flare", "Cut to frame 1",
          "a wooden match being struck in slow motion, bright flare")],
 sound="A soft hiss, then a clean ignition pop; a match strike on the last line.",
 title="The Lighter Was Invented Before the Match",
 desc="Döbereiner's self-lighting lamp: 1823. John Walker's friction match: 1826. Older Than You Think #18.",
 tags=["history", "inventions", "science"],
 comment="What invention do you think came first, but didn't?",
 cta="#19: Rome taxed urine - because it washed their clothes.",
 loop="The match flare cuts back to the lamp's flame.",
 length="~27s", exp="Everyday-object reversal", metric="Comments per 1,000 views"),

dict(day=10, n=19, cat="Rome", hooktype="Rome doing something disgusting and clever",
 topic="Rome taxed urine because it cleaned their clothes",
 claim="Roman fullers (laundries, fullonicae) used stale urine, whose ammonia cleans and whitens cloth; urine was collected from pots set out in the street. Emperor Vespasian taxed its collection, and according to Suetonius, when his son Titus objected he held a coin to Titus's nose and asked whether it smelled - the origin of 'pecunia non olet', money does not stink.",
 sources=[("Pecunia non olet - overview with references (Suetonius, Vespasian 23)", "https://en.wikipedia.org/wiki/Pecunia_non_olet"),
          ("Fullonica - overview with references", "https://en.wikipedia.org/wiki/Fullonica")],
 frame="A row of stone vats in a Roman laundry in Pompeii, bright light. Text: ROME TAXED URINE.",
 hook="Rome taxed urine - because it washed their clothes.",
 script=[("0.0-2.5", "Rome taxed urine - because it washed their clothes."),
         ("2.5-8.0", "Roman laundries soaked cloth in stale urine. The ammonia in it lifted out dirt and grease."),
         ("8.0-19.0", "Shops set out pots in the street for people to fill, and the laundries collected them. Emperor Vespasian put a tax on it. When his son complained, Vespasian held a coin to his nose and asked if it smelled."),
         ("19.0-24.0", "Two thousand years later, 'money doesn't smell' is still a saying.")],
 osd=[("0.0-2.5", "ROME TAXED\nURINE"), ("2.5-8.0", "ammonia cleans cloth"), ("8.0-13.0", "street collection pots"),
      ("13.0-19.0", "Vespasian's tax"), ("19.0-24.0", "money doesn't smell")],
 shots=[S("0-2.5s", "Roman laundry vats", "Stone vats in a row", "Slow push", "Bright daylight", "Hard cut",
          "a row of stone washing vats in a Roman fullonica in Pompeii, bright daylight"),
        S("2.5-8s", "Cloth being trodden", "Worker in a vat", "Static", "Warm", "Crossfade",
          "a Roman laundry worker treading cloth in a stone vat, warm light"),
        S("8-19s", "Clay pot in a street", "Pot by a shop door", "Slow push", "Morning", "Match cut",
          "a large clay pot beside a shop doorway on an ancient Roman street, morning light"),
        S("19-23s", "Roman coin", "Coin close", "Slow rotate", "Raking light", "Cut to frame 1",
          "a Roman silver coin with an emperor's portrait, raking light, macro")],
 sound="Water sloshing, a comic pause before the coin line.",
 title="Rome Taxed Urine 2,000 Years Ago - Because It Washed Their Clothes",
 desc="Roman laundries cleaned cloth with urine, and Vespasian taxed it - 'money doesn't smell'. Older Than You Think #19.",
 tags=["history", "rome", "funny"],
 comment="What's the strangest thing people used to clean with?",
 cta="#20: Napoleon wasn't short.",
 loop="The coin cuts back to the laundry vats.",
 length="~27s", exp="Rome + humour", metric="Comments per 1,000 views"),

dict(day=10, n=20, cat="Myth-busting", hooktype="'You were taught wrong' about a famous person",
 topic="Napoleon wasn't short",
 claim="Napoleon was about 1.69 m (5 ft 7 in), average or slightly above for a Frenchman of his era. His recorded height of 5 ft 2 in was in French units (pieds and pouces), which were longer than English ones, and British caricaturists such as James Gillray drew him tiny.",
 sources=[("Britannica: Napoleon I", "https://www.britannica.com/biography/Napoleon-I"),
          ("Napoleon complex - overview with references", "https://en.wikipedia.org/wiki/Napoleon_complex")],
 frame="A full-length portrait-style image of Napoleon standing beside a height marker at average height. Text: NOT SHORT.",
 hook="Napoleon wasn't short.",
 script=[("0.0-2.0", "Napoleon wasn't short."),
         ("2.0-7.0", "He was about 1.69 meters - five foot seven. Average, or a little taller, for a Frenchman of his time."),
         ("7.0-19.0", "The myth came from two places. French inches were longer than English ones, so his recorded five-foot-two was mistranslated. And British cartoonists drew him tiny on purpose."),
         ("19.0-23.0", "The most famous short man in history was a propaganda cartoon.")],
 osd=[("0.0-2.0", "NOT SHORT"), ("2.0-7.0", "~1.69 m / 5'7\""), ("7.0-13.0", "French inches were longer"),
      ("13.0-19.0", "British cartoons"), ("19.0-23.0", "propaganda")],
 shots=[S("0-2s", "Napoleon full length", "Standing figure", "Slow push", "Warm portrait light", "Hard cut",
          "a full length painted-portrait style image of Napoleon Bonaparte in uniform standing in a palace hall, warm light"),
        S("2-7s", "Soldiers in line", "Row of soldiers", "Tracking", "Morning light", "Crossfade",
          "a line of early 19th century French soldiers standing at attention, Napoleon among them at the same height"),
        S("7-19s", "Old measuring rulers", "Two rulers side by side", "Slow pan", "Desk lamp", "Match cut",
          "two antique measuring rulers side by side on a desk, one French and one English, desk lamp light"),
        S("19-23s", "Satirical print", "Cartoon on a table", "Slow push", "Soft", "Cut to frame 1",
          "an old hand-coloured satirical print lying on a wooden table, soft light")],
 sound="Military snare, a comic pause before 'propaganda cartoon'.",
 title="Napoleon Wasn't Short - British Cartoonists Made Him Tiny",
 desc="Napoleon was about 1.69 m, average for his era; French units and British caricature made him 'short'. Older Than You Think #20.",
 tags=["history", "napoleon", "myths"],
 comment="Did you grow up thinking Napoleon was short?",
 cta="#21: the shortest war in history lasted about 38 minutes.",
 loop="The satirical print cuts back to the full-height portrait.",
 length="~26s", exp="Famous-person myth", metric="Shares per 1,000 views"),

dict(day=11, n=21, cat="Modern history", hooktype="A record with a number",
 topic="The shortest war in history",
 claim="The Anglo-Zanzibar War of 27 August 1896 is usually recorded as the shortest war in history, lasting between about 38 and 45 minutes: after Sultan Khalid bin Barghash took power without British approval and an ultimatum expired at 9:00, British ships bombarded the palace and the fighting ended within the hour.",
 sources=[("Anglo-Zanzibar War - overview with references", "https://en.wikipedia.org/wiki/Anglo-Zanzibar_War"),
          ("Guinness World Records: shortest war", "https://www.guinnessworldrecords.com/world-records/shortest-war")],
 frame="A white palace on a tropical shore with warships offshore under a clear sky. Text: 38 MINUTES.",
 hook="The shortest war in history lasted about 38 minutes.",
 script=[("0.0-2.5", "The shortest war in history lasted about 38 minutes."),
         ("2.5-7.0", "Zanzibar, 27 August 1896. A new sultan took power without British approval."),
         ("7.0-19.0", "Britain gave him an ultimatum. When it ran out at nine in the morning, the warships opened fire on the palace. Before ten o'clock, the flag was down and the war was over."),
         ("19.0-23.0", "Some records say 45 minutes. Either way - less than an hour.")],
 osd=[("0.0-2.5", "38 MINUTES"), ("2.5-7.0", "Zanzibar, 1896"), ("7.0-13.0", "ultimatum: 9:00 am"),
      ("13.0-19.0", "over before 10"), ("19.0-23.0", "under an hour")],
 shots=[S("0-2.5s", "Palace and warships", "Palace foreground, ships offshore", "Slow push", "Bright tropical sun", "Hard cut",
          "a white 19th century palace on a tropical shore with steam warships anchored offshore under a clear sky"),
        S("2.5-7s", "Stone Town street", "Narrow street", "Tracking", "Warm", "Crossfade",
          "a narrow street in 1890s Zanzibar Stone Town, warm light"),
        S("7-19s", "Warship guns", "Deck guns close", "Slow push", "Morning haze", "Match cut",
          "the deck guns of an 1890s steam warship in morning haze"),
        S("19-23s", "Pocket watch", "Watch face close", "Static", "Soft", "Cut to frame 1",
          "an antique pocket watch showing 9:40, soft light")],
 sound="A clock ticking throughout; distant cannon at 'opened fire'; silence at the end.",
 title="The Shortest War in History Lasted About 38 Minutes",
 desc="The Anglo-Zanzibar War of 1896 lasted between about 38 and 45 minutes. Older Than You Think #21.",
 tags=["history", "war", "records"],
 comment="What's the shortest thing you've ever quit?",
 cta="#22: people were making toothpaste 1,600 years ago.",
 loop="The pocket watch cuts back to the palace at nine.",
 length="~26s", exp="Record with a number (new subject family)", metric="Views vs channel median"),

dict(day=11, n=22, cat="Everyday life", hooktype="Your routine is ancient",
 topic="A 1,600-year-old toothpaste recipe",
 claim="A papyrus from Roman-era Egypt, dated to the 4th century AD and held in Vienna, records a recipe for a tooth powder of rock salt, mint, dried iris flower and grains of pepper. A dentist who tried it in 2003 reported it made his gums bleed but left his mouth fresh and clean (BBC News).",
 sources=[("BBC News (2003): Ancient Egyptian toothpaste recipe", "http://news.bbc.co.uk/2/hi/europe/2786525.stm")],
 note="Say 'a papyrus from Roman Egypt' - it is 4th century AD, not pharaonic Egypt.",
 frame="A fragment of ancient papyrus with faded writing beside a small bowl of white powder and mint leaves. Text: 1,600-YEAR-OLD TOOTHPASTE.",
 hook="People were making toothpaste 1,600 years ago.",
 script=[("0.0-2.5", "People were making toothpaste 1,600 years ago."),
         ("2.5-8.0", "A papyrus from Roman Egypt, written in the 4th century, gives the recipe for a powder for white and perfect teeth."),
         ("8.0-19.0", "Rock salt, mint, dried iris flower and grains of pepper, crushed together. A dentist who tried it in 2003 said it made his gums bleed - but left his mouth fresh and clean."),
         ("19.0-23.0", "Your morning routine is older than you think.")],
 osd=[("0.0-2.5", "1,600-YEAR-OLD\nTOOTHPASTE"), ("2.5-8.0", "papyrus, 4th century"), ("8.0-13.0", "salt, mint, iris, pepper"),
      ("13.0-19.0", "tested in 2003"), ("19.0-23.0", "older than you think")],
 shots=[S("0-2.5s", "Papyrus and powder", "Papyrus + bowl", "Slow push", "Warm raking light", "Hard cut",
          "a fragment of ancient papyrus with faded Greek writing beside a small clay bowl of white powder and fresh mint leaves, warm raking light"),
        S("2.5-8s", "Scribe writing", "Hands on papyrus", "Static", "Lamplight", "Crossfade",
          "a scribe's hands writing on papyrus with a reed pen by oil lamp light"),
        S("8-19s", "Ingredients crushed", "Mortar and pestle", "Top-down", "Soft", "Match cut",
          "rock salt, mint leaves, dried purple iris petals and peppercorns in a stone mortar, top-down"),
        S("19-23s", "Modern toothbrush", "Close", "Static", "Bright bathroom", "Cut to frame 1",
          "a modern toothbrush with toothpaste on a bathroom sink, bright clean light")],
 sound="Mortar-and-pestle grind as rhythm; a bright mint 'ding' on 'fresh and clean'.",
 title="People Made Toothpaste 1,600 Years Ago - Here's the Recipe",
 desc="A 4th-century papyrus from Roman Egypt records a tooth powder of rock salt, mint, iris and pepper. Older Than You Think #22. Source: BBC News (2003).",
 tags=["history", "ancient", "everydaylife"],
 comment="Would you try the 1,600-year-old toothpaste?",
 cta="#23: Russia's Olympic team arrived twelve days late because of its calendar.",
 loop="The modern toothbrush cuts back to the ancient powder.",
 length="~26s", exp="Everyday-life antiquity (a new subject family)", metric="Comments per 1,000 views"),

dict(day=12, n=23, cat="Modern history", hooktype="Absurd true story",
 topic="Russia arrived 12 days late to the 1908 Olympics",
 claim="At the 1908 London Olympics, Russia's shooting team arrived late - by twelve days, in the usual telling - because Russia still used the Julian calendar, which by then ran thirteen days behind the Gregorian calendar used in Britain. Russia adopted the Gregorian calendar in 1918.",
 sources=[("Russia at the 1908 Summer Olympics - overview with references", "https://en.wikipedia.org/wiki/Russia_at_the_1908_Summer_Olympics"),
          ("Britannica: Gregorian calendar", "https://www.britannica.com/topic/Gregorian-calendar")],
 note="The '12 days' figure is the standard telling; the calendars were 13 days apart in 1908. The script says the calendar was almost two weeks behind.",
 frame="An Edwardian-era athlete with a rifle arriving at an empty stadium, a torn calendar page in the foreground. Text: 12 DAYS LATE.",
 hook="Russia's Olympic team arrived twelve days late - because of their calendar.",
 script=[("0.0-3.0", "Russia's Olympic team arrived twelve days late - because of their calendar."),
         ("3.0-8.0", "London, 1908. Russia still used the old Julian calendar. Britain used the Gregorian one."),
         ("8.0-19.0", "By then the two were almost two weeks apart. Russia's shooters planned by their own dates, and turned up after their events were over."),
         ("19.0-23.0", "Russia didn't switch calendars until 1918 - after the revolution.")],
 osd=[("0.0-3.0", "12 DAYS LATE"), ("3.0-8.0", "London, 1908"), ("8.0-13.0", "Julian vs Gregorian"),
      ("13.0-19.0", "events already over"), ("19.0-23.0", "switched in 1918")],
 shots=[S("0-3s", "Athlete at empty stadium", "Figure from behind", "Slow push", "Grey London light", "Hard cut",
          "an Edwardian era athlete seen from behind carrying a rifle case into an empty 1908 London stadium, grey light"),
        S("3-8s", "1908 stadium", "Wide", "Aerial drift", "Overcast", "Crossfade",
          "the White City stadium in London in 1908, wide, overcast"),
        S("8-19s", "Two calendars", "Pages side by side", "Slow pan", "Desk lamp", "Match cut",
          "two old paper calendars side by side on a desk showing different dates, desk lamp light"),
        S("19-23s", "Petrograd 1918", "Street scene", "Slow push", "Cold light", "Cut to frame 1",
          "a snowy Petrograd street in 1918, cold light")],
 sound="Stopwatch ticking, a crowd roar that fades to silence as they arrive.",
 title="Russia's Olympic Team Arrived 12 Days Late Because of Its Calendar",
 desc="Russia still used the Julian calendar at the 1908 London Olympics - and its shooters arrived after their events. Older Than You Think #23.",
 tags=["history", "olympics", "funny"],
 comment="What's the latest you've ever been to something important?",
 cta="#24: the people who built the pyramids weren't slaves.",
 loop="Petrograd cuts back to the empty stadium.",
 length="~26s", exp="Absurd modern-history story", metric="Shares per 1,000 views"),

dict(day=12, n=24, cat="Egypt", hooktype="'You were taught wrong' with evidence",
 topic="The pyramid builders weren't slaves",
 claim="Excavations beside the Giza plateau by Mark Lehner's AERA team and Zahi Hawass uncovered the town and cemetery of the pyramid builders: bakeries, food-processing areas, and tombs near the pyramids. Workers' skeletons show healed fractures and survived amputations, evidence of medical care. Egyptologists now describe them as paid or conscripted labourers rather than slaves.",
 sources=[("AERA - Ancient Egypt Research Associates: the Lost City of the Pyramid Builders", "https://www.aeraweb.org/lost-city-project/"),
          ("National Geographic (2010): tombs of the pyramid builders", "https://www.nationalgeographic.com/history/article/100112-egypt-pyramid-builders-tombs")],
 frame="Ancient mud-brick bakery ruins with bread moulds, the Great Pyramid behind. Text: NOT SLAVES.",
 hook="The people who built the pyramids weren't slaves.",
 script=[("0.0-2.5", "The people who built the pyramids weren't slaves."),
         ("2.5-7.0", "Archaeologists found their town beside the Giza plateau - with bakeries and kitchens that fed thousands."),
         ("7.0-19.0", "Their skeletons show broken bones that healed and even amputations they survived - someone was treating them. And they were buried in tombs next to the pyramids, with bread and beer for the afterlife."),
         ("19.0-23.0", "Slaves don't get buried beside the king.")],
 osd=[("0.0-2.5", "NOT SLAVES"), ("2.5-7.0", "a town with bakeries"), ("7.0-13.0", "healed bones"),
      ("13.0-19.0", "tombs by the pyramids"), ("19.0-23.0", "buried beside the king")],
 shots=[S("0-2.5s", "Bakery ruins and pyramid", "Ruins foreground", "Slow push", "Warm desert light", "Hard cut",
          "ancient mud-brick bakery ruins with conical bread moulds, the Great Pyramid in the background, warm desert light"),
        S("2.5-7s", "Workers' town", "Reconstruction", "Aerial drift", "Golden hour", "Crossfade",
          "reconstruction of the ancient pyramid builders' town at Giza with bakeries and smoke rising, golden hour"),
        S("7-19s", "Workers' tomb", "Small tomb", "Slow push", "Low sun", "Match cut",
          "a small mud-brick tomb of a pyramid worker in the desert, low sun"),
        S("19-23s", "Great Pyramid", "Pyramid wide", "Slow tilt", "Bright", "Cut to frame 1",
          "the Great Pyramid of Giza in bright sunlight, wide")],
 sound="Desert wind, bread-oven crackle, a low hit on 'slaves don't'.",
 title="The Pyramid Builders Weren't Slaves - They Had Bakeries and Medical Care",
 desc="The builders' town at Giza had bakeries; their skeletons show medical care; they were buried beside the pyramids. Older Than You Think #24. Sources: AERA, National Geographic.",
 tags=["history", "egypt", "myths"],
 comment="Did you learn in school that slaves built the pyramids?",
 cta="More next week - the past keeps doing things we think are modern.",
 loop="The pyramid cuts back to the builders' bakery in front of it.",
 length="~26s", exp="Myth-busting on the channel's strongest subject (Egypt)", metric="Subscribers per 1,000 views"),
]

REALS2 = {
    15: ["Eiffel Tower summer", "Eiffel Tower structure", "Eiffel Tower sunset", "Eiffel Tower snow"],
    16: ["Alexander Bain telegraph", "telegraph apparatus 19th century", "telegraph poles", "Bell telephone 1876"],
    17: ["woolly mammoth", "Wrangel Island", "Great Pyramid of Giza", "woolly mammoth tusk"],
    18: ["Döbereiner's lamp", "Johann Wolfgang Döbereiner", None, "matchstick"],
    19: ["Fullonica Stephani Pompeii", "Fullonica Pompeii", None, "Vespasian denarius"],
    20: ["Napoleon portrait Jacques-Louis David", None, None, "James Gillray Napoleon"],
    21: ["Sultan palace Zanzibar 1896", "Stone Town Zanzibar", "HMS St George 1896", "pocket watch antique"],
    22: [None, "papyrus Roman Egypt", "rock salt", "toothbrush"],
    23: ["1908 Summer Olympics", "White City Stadium 1908", None, "Petrograd 1918"],
    24: ["Giza bakery bread moulds", "Heit el-Ghurab", "tombs of the pyramid builders Giza", "Great Pyramid of Giza"],
}
