# -*- coding: utf-8 -*-
# Rise With Fate - "Your Mind, Measured" - 14 Shorts. Each is one published study
# about the viewer. Faceless: silhouettes, hands, backs, objects - never a face.

V = "vertical 9:16, photorealistic, cinematic, warm sunrise palette, shallow depth of field, no identifiable faces, no text, no watermark"

def S(t, subj, comp, move, light, trans, prompt):
    return dict(t=t, subj=subj, comp=comp, move=move, light=light, trans=trans, prompt=prompt + ", " + V)

SHORTS = [
dict(day=1, n=1, cat="Social anxiety", hooktype="Relief statement about the viewer",
 topic="The spotlight effect: people notice you far less than you think",
 claim="In Gilovich, Medvec & Savitsky (2000), students who wore an embarrassing T-shirt into a room estimated that about half of the people there noticed it; about a quarter actually did.",
 sources=[("Gilovich, Medvec & Savitsky 2000, J. Personality & Social Psychology 78(2)","https://pubmed.ncbi.nlm.nih.gov/10707330/")],
 frame="A lone figure seen from behind on a small stage under one hard spotlight; the seats beyond are dim and the few people in them are looking down at their phones. Text: NOBODY'S WATCHING THIS CLOSELY.",
 hook="Half as many people noticed as you think.",
 script=[("0.0-1.5","Half as many people noticed as you think."),
         ("1.5-5.0","In a Cornell study, students walked into a room wearing an embarrassing T-shirt."),
         ("5.0-15.0","They guessed half the room noticed. Actually: about a quarter. It's called the spotlight effect: you feel lit up, while everyone else is busy thinking about themselves."),
         ("15.0-20.0","That thing you said yesterday? Most people have already forgotten it.")],
 osd=[("0.0-1.5","HALF AS MANY\nNOTICED"),("1.5-5.0","embarrassing T-shirt test"),("5.0-9.0","they guessed: ~50%"),("9.0-15.0","reality: ~25%"),("15.0-20.0","already forgotten")],
 shots=[S("0-1.5s","Figure under spotlight","Figure small, centre, from behind","Slow push-in","Single hard spotlight, dark room","Hard cut","a lone person seen from behind standing on a small stage under a single hard spotlight, dim auditorium, the few audience members looking down at glowing phones"),
        S("1.5-5s","Door opening into a busy room","Over-the-shoulder, no faces","Walk-in steadicam","Warm interior","Crossfade 0.3s","over-the-shoulder view walking through a doorway into a busy university common room, people turned away talking to each other"),
        S("5-15s","Crowd, each in their own world","Wide, people turned away","Slow lateral dolly","Soft window light","Match cut","a crowded cafe seen from above, every person absorbed in their own laptop, phone or conversation, nobody looking up"),
        S("15-20s","Empty stage","Same stage, spotlight fading","Slow pull back","Spotlight dimming","Cut to frame 1","an empty small stage with a single spotlight slowly fading, dim empty seats")],
 sound="Soft room tone and a low heartbeat that slows as the numbers land. Warm piano enters at 'already forgotten'.",
 title="People Notice You About Half as Much as You Think",
 desc="In a Cornell study, people guessed half the room noticed their embarrassing shirt. About a quarter did. Your Mind, Measured #1. Source: Gilovich et al., JPSP (2000).",
 tags=["psychology","anxiety","selfimprovement"],
 comment="What's the thing you still cringe about that nobody else remembers?",
 cta="#2 is one sentence that 94 studies tested for actually following through.",
 loop="The fading spotlight on the empty stage returns to the lit stage of frame 1.",
 length="~20s", exp="Control: second-person relief statement (the channel's best-converting shape)", metric="Subscribers per 1,000 views"),

dict(day=1, n=2, cat="Goals / habits", hooktype="Fill-in-the-blank the viewer completes",
 topic="If-then plans (implementation intentions)",
 claim="A meta-analysis of 94 independent tests (Gollwitzer & Sheeran, 2006) found that forming an if-then plan - 'When situation X arises, I will do Y' - had a medium-to-large effect on reaching goals (d = 0.65).",
 sources=[("Gollwitzer & Sheeran 2006, Advances in Experimental Social Psychology 38","https://doi.org/10.1016/S0065-2601(06)38002-1")],
 frame="A hand writing on a sticky note stuck to a bathroom mirror: 'WHEN ____, I WILL ____.' Text: YOUR GOAL IS MISSING THIS.",
 hook="Your goal is missing one sentence.",
 script=[("0.0-1.5","Your goal is missing one sentence."),
         ("1.5-5.0","Not 'I'll work out more.' This: when this happens, I will do that."),
         ("5.0-15.0","When I get home, I put my shoes on. It's called an if-then plan. Across 94 studies, people who made one reached their goals clearly more often."),
         ("15.0-20.0","Write yours in the comments. Right now. That is the plan.")],
 osd=[("0.0-1.5","MISSING\nONE SENTENCE"),("1.5-5.0","WHEN ___\nI WILL ___"),("5.0-10.0","'when I get home,\nshoes on'"),("10.0-15.0","tested in 94 studies"),("15.0-20.0","write yours below")],
 shots=[S("0-1.5s","Sticky note on mirror","Hand and note, mirror reflection blurred","Static","Morning bathroom light","Hard cut","a hand writing WHEN and I WILL on a yellow sticky note on a bathroom mirror, the reflection soft and out of focus, morning light"),
        S("1.5-5s","Crossed-out vague goal","Notebook top-down","Slow push","Desk lamp","Crossfade","top-down view of a notebook where a vague goal is crossed out and replaced with a specific plan, pen in hand"),
        S("5-15s","Shoes by the door","Low angle at door","Slow dolly toward shoes","Warm evening light","Match cut","running shoes waiting by a front door at golden hour, a work bag being dropped beside them, low angle"),
        S("15-20s","Phone typing","Hands and screen, no face","Static","Warm lamp","Cut to frame 1","two hands typing on a phone keyboard in a warm lit room, screen glow")],
 sound="Pencil scratch on the first frame. Light, steady beat that locks in on 'when... I will'.",
 title="94 Studies Tested This One Sentence for Reaching Goals",
 desc="If-then plans - 'When X happens, I will do Y' - had a medium-to-large effect across 94 studies. Your Mind, Measured #2. Source: Gollwitzer & Sheeran (2006).",
 tags=["goals","habits","motivation"],
 comment="Finish it: 'When ___, I will ___.'",
 cta="#3: why starting on Monday isn't just an excuse - researchers measured it.",
 loop="The typed comment returns to the handwritten note: the plan written twice.",
 length="~20s", exp="Comment trigger built into the script (the viewer writes their plan)", metric="Comments per 1,000 views"),

dict(day=2, n=3, cat="Motivation", hooktype="Validates something viewers feel guilty about",
 topic="The fresh start effect",
 claim="Dai, Milkman & Riis (2014) found Google searches for 'diet' rise at the start of weeks, months and years, and gym visits rise after temporal landmarks such as a new week, month, semester or birthday.",
 sources=[("Dai, Milkman & Riis 2014, Management Science 60(10)","https://doi.org/10.1287/mnsc.2014.1901")],
 frame="A wall calendar with MONDAY circled in red marker, sunrise light across it. Text: MONDAY IS REAL.",
 hook="Starting on Monday isn't just an excuse.",
 script=[("0.0-1.5","Starting on Monday isn't just an excuse."),
         ("1.5-5.0","Wharton researchers tracked what people do when a new week begins."),
         ("5.0-15.0","Searches for 'diet' jump at the start of every week, month and year. Gym visits rise after a birthday. It's the fresh start effect. The old you feels like someone else."),
         ("15.0-20.0","So pick your Monday. Then show up on it.")],
 osd=[("0.0-1.5","MONDAY\nIS REAL"),("1.5-5.0","Wharton research"),("5.0-10.0","'diet' searches jump"),("10.0-15.0","gym visits rise"),("15.0-20.0","pick your Monday")],
 shots=[S("0-1.5s","Calendar with Monday circled","Calendar fills frame","Slow push","Sunrise raking light","Hard cut","a paper wall calendar with Monday circled in red marker, early sunrise light raking across it"),
        S("1.5-5s","Search bar","Laptop screen, hands","Static","Screen glow in dark room","Crossfade","hands on a laptop in a dark room, a search bar glowing on the screen, soft screen light"),
        S("5-15s","Gym at dawn","Wide, figures from behind","Slow dolly","Cool dawn light","Whip cut","people seen from behind walking into a bright gym at dawn, cool morning light through big windows"),
        S("15-20s","Sunrise, figure walking","Silhouette on a road","Tracking alongside","Golden sunrise","Cut to frame 1","a silhouetted person walking along an empty road toward a rising sun")],
 sound="Alarm-clock chime at 0.3s, then a rising, hopeful synth. A 'page turn' on 'new chapter'.",
 title="Starting on Monday Isn't Just an Excuse. Researchers Measured It.",
 desc="Diet searches and gym visits rise at the start of each week, month and year - the fresh start effect. Your Mind, Measured #3. Source: Management Science (2014).",
 tags=["motivation","mindset","psychology"],
 comment="What's the one thing you're starting next Monday?",
 cta="#4: the easiest way to get better ideas - and it isn't coffee.",
 loop="The sunrise walk returns to the sunlit calendar.",
 length="~21s", exp="'You're not lazy' validation angle", metric="Shares per 1,000 views"),

dict(day=2, n=4, cat="Creativity", hooktype="Instruction + number",
 topic="Walking raises creative output",
 claim="Oppezzo & Schwartz (2014, Stanford) found participants produced on average about 60% more creative ideas (alternate-uses test) while walking than while sitting, including on a treadmill facing a blank wall, with a boost that carried over when they sat back down.",
 sources=[("Oppezzo & Schwartz 2014, J. Experimental Psychology: Learning, Memory & Cognition","https://doi.org/10.1037/a0036577"),
          ("Stanford Report: Stanford study finds walking improves creativity","https://news.stanford.edu/stories/2014/04/walking-vs-sitting-042414")],
 frame="A pair of sneakers mid-stride on a leafy path, sun flaring through the trees. Text: STUCK? STAND UP.",
 hook="Stuck on a problem? Stand up.",
 script=[("0.0-1.5","Stuck on a problem? Stand up."),
         ("1.5-5.0","Stanford researchers asked people to invent new uses for ordinary objects."),
         ("5.0-15.0","Some sat. Some walked, even on a treadmill facing a blank wall. The walkers came up with about 60 percent more creative ideas. And the boost stayed when they sat back down."),
         ("15.0-20.0","Your next good idea might be one walk away.")],
 osd=[("0.0-1.5","STUCK?\nSTAND UP"),("1.5-5.0","Stanford test"),("5.0-10.0","sitting vs walking"),("10.0-15.0","~60% more ideas"),("15.0-20.0","one walk away")],
 shots=[S("0-1.5s","Sneakers mid-stride","Feet only, low","Tracking","Dappled sun, lens flare","Hard cut","close low shot of sneakers mid-stride on a leafy park path, dappled sunlight and a soft lens flare"),
        S("1.5-5s","Paperclip and brick on desk","Objects top-down","Slow rotate","Soft studio","Crossfade","a paperclip, a brick and a cup arranged on a clean desk, top-down, soft studio light"),
        S("5-15s","Treadmill facing wall","Figure from behind","Static wide","Flat white light","Match cut","a person seen from behind walking on a treadmill facing a plain white wall in a bare room"),
        S("15-20s","Walker on a city street","Silhouette, city","Tracking","Golden hour","Cut to frame 1","a silhouetted person walking through a city street at golden hour, long shadows")],
 sound="Footsteps as rhythm from 0s; music built on the walking tempo. A bright 'ding' on '60 percent'.",
 title="Walking Raised Creative Ideas by About 60% in a Stanford Study",
 desc="People came up with about 60% more creative ideas while walking than sitting. Your Mind, Measured #4. Source: Oppezzo & Schwartz (2014).",
 tags=["creativity","productivity","mindset"],
 comment="Where do your best ideas show up - shower, walk, or 3 a.m.?",
 cta="#5: what 17 hours awake does to your brain. It's been compared to alcohol.",
 loop="The city walk matches the stride of frame 1.",
 length="~19s", exp="Actionable instruction as the hook", metric="Average percentage viewed"),

dict(day=3, n=5, cat="Sleep / health", hooktype="Shock comparison tied to the viewer's own day",
 topic="17-19 hours awake vs 0.05% blood alcohol",
 claim="Williamson & Feyer (2000) found that after 17-19 hours without sleep, performance on some tests was equivalent to or worse than at a blood alcohol concentration of 0.05%.",
 sources=[("Williamson & Feyer 2000, Occupational & Environmental Medicine 57(10)","https://pubmed.ncbi.nlm.nih.gov/10984335/")],
 note="0.05% is the drink-driving limit in Australia and much of Europe; the US limit is 0.08%. The script says 'many countries', not the US.",
 frame="A bedside clock reading 12:00 AM beside a glowing phone and a glass of water. Text: 17 HOURS AWAKE.",
 hook="Seventeen hours awake, and your brain can test like you've been drinking.",
 script=[("0.0-2.0","Seventeen hours awake, and your brain can test like you've been drinking."),
         ("2.0-5.0","Researchers kept people awake and compared them with people given alcohol."),
         ("5.0-15.0","After 17 to 19 hours awake, some scores matched a blood alcohol level of 0.05 percent. Some were worse. In many countries, that's the driving limit."),
         ("15.0-20.0","If you woke up at 7, that's midnight tonight.")],
 osd=[("0.0-2.0","17 HOURS\nAWAKE"),("2.0-5.0","sleep vs alcohol test"),("5.0-11.0","= 0.05% alcohol"),("11.0-15.0","legal limit in many countries"),("15.0-20.0","woke at 7?\nthat's midnight")],
 shots=[S("0-2s","Bedside clock + glowing phone","Clock foreground","Static, slight drift","Blue phone glow, dark","Hard cut","a bedside digital clock showing 12:00 AM next to a glowing phone and a glass of water in a dark bedroom"),
        S("2-5s","Test in a lab","Hands on a keyboard","Slow push","Clinical light","Crossfade","hands pressing a key on a reaction-time test in a clinical lab, screen with a simple target"),
        S("5-15s","Night road through windscreen","Driver POV, no face","Slow forward","Streetlights smearing","Match cut","a first-person view through a car windscreen on a dark highway at night, streetlights blurring"),
        S("15-20s","Clock rolling to midnight","Clock close-up","Timelapse","Dark bedroom","Cut to frame 1","a bedside clock ticking over to 12:00 AM in a dark room")],
 sound="Low hum, slightly detuned (woozy). A single glass 'clink' on '0.05'. Silence before 'midnight tonight'.",
 title="17 Hours Awake Scored Like a 0.05% Blood Alcohol Level",
 desc="After 17-19 hours without sleep, some test scores matched a blood alcohol level of 0.05%. Your Mind, Measured #5. Source: Occupational & Environmental Medicine (2000).",
 tags=["sleep","health","brain"],
 comment="What time did you wake up today? Do the math.",
 cta="#6: why calling yourself by your own name calms you down.",
 loop="The clock hitting midnight returns to the midnight clock of frame 1.",
 length="~20s", exp="Personal math in the last line (makes the fact about the viewer's night)", metric="Viewed vs swiped"),

dict(day=3, n=6, cat="Confidence", hooktype="Counter-intuitive instruction",
 topic="Distanced (third-person) self-talk",
 claim="Kross et al. (2014) found that people who referred to themselves by their own name or 'you' instead of 'I' before giving a speech felt less anxious and were rated by judges as performing better.",
 sources=[("Kross et al. 2014, J. Personality & Social Psychology 106(2)","https://pubmed.ncbi.nlm.nih.gov/24467424/")],
 frame="A person's back as they stand at the edge of a stage curtain, a spotlit microphone waiting beyond. Text: STOP SAYING 'I'.",
 hook="When you're nervous, stop saying 'I'.",
 script=[("0.0-1.5","When you're nervous, stop saying 'I'."),
         ("1.5-5.0","Michigan researchers had people give a speech with almost no time to prepare."),
         ("5.0-15.0","Some talked to themselves as 'I'. Others used their own name: why is Sarah nervous? The name group felt less anxious, and judges rated their speeches better."),
         ("15.0-20.0","Before your next hard thing, say your name. Talk to yourself like a friend.")],
 osd=[("0.0-1.5","STOP SAYING 'I'"),("1.5-5.0","surprise speech test"),("5.0-10.0","'I' vs your name"),("10.0-15.0","less anxious\nbetter speeches"),("15.0-20.0","say your name")],
 shots=[S("0-1.5s","Backstage edge","From behind, curtain edge","Slow push toward the light","Warm spotlight beyond","Hard cut","a person seen from behind waiting at the edge of a velvet stage curtain, a spotlit microphone beyond"),
        S("1.5-5s","Blank page, clock","Top-down desk","Static","Tense cool light","Crossfade","a blank sheet of paper and a ticking stopwatch on a desk, cool light"),
        S("5-15s","Mirror, blurred reflection","Shoulder and blurred mirror","Slow rack focus","Soft","Match cut","over-the-shoulder view of a person in front of a mirror, the reflection completely out of focus, soft light"),
        S("15-20s","Walking onto stage","From behind, into light","Tracking","Spotlight flare","Cut to frame 1","a person seen from behind walking out onto a bright stage into a spotlight flare")],
 sound="Crowd murmur low; heartbeat that slows on 'less anxious'. A warm swell on the walk-out.",
 title="Talking to Yourself by Name Made People Calmer Before a Speech",
 desc="People who used their own name in self-talk felt less anxious and gave better speeches. Your Mind, Measured #6. Source: Kross et al., JPSP (2014).",
 tags=["confidence","anxiety","psychology"],
 comment="Write what you'd tell yourself - using your own name.",
 cta="#7: where your mind goes almost half the time you're awake.",
 loop="The walk into the spotlight becomes the waiting figure again.",
 length="~20s", exp="Instruction the viewer can try in the comments", metric="Comments per 1,000 views"),

dict(day=4, n=7, cat="Happiness", hooktype="'Right now' about the viewer",
 topic="Mind-wandering nearly half of waking time",
 claim="Killingsworth & Gilbert (2010) sampled thousands of adults through a phone app: minds wandered 46.9% of the time, and people were less happy while mind-wandering; even pleasant wandering did not make them happier than staying on task.",
 sources=[("Killingsworth & Gilbert 2010, Science 330(6006)","https://www.science.org/doi/10.1126/science.1192439"),
          ("Harvard Gazette: A wandering mind is an unhappy one","https://news.harvard.edu/gazette/story/2010/11/wandering-mind-not-a-happy-mind/")],
 frame="A person from behind on a bus, looking out of a rain-streaked window, a ghosted double exposure of a beach in the glass. Text: YOU'RE NOT HERE.",
 hook="Almost half the time you're awake, you're not really here.",
 script=[("0.0-1.8","Almost half the time you're awake, you're not really here."),
         ("1.8-5.0","Harvard researchers pinged thousands of people's phones at random moments."),
         ("5.0-15.0","What are you doing? Are you thinking about it? 46.9 percent of the time, the answer was no. And wandering minds were less happy."),
         ("15.0-20.0","Wherever you are right now, be there. You're here. Good.")],
 osd=[("0.0-1.8","YOU'RE\nNOT HERE"),("1.8-5.0","random phone check-ins"),("5.0-10.0","46.9% of the time"),("10.0-15.0","less happy"),("15.0-20.0","be here")],
 shots=[S("0-1.8s","Bus window double exposure","From behind, window","Slow drift","Grey rain light","Hard cut","a person seen from behind on a bus looking out of a rain-streaked window, a faint double exposure of a beach reflected in the glass"),
        S("1.8-5s","Phone buzzing on table","Phone close-up","Static","Soft daylight","Crossfade","a phone lighting up and buzzing on a wooden table, soft daylight"),
        S("5-15s","Hands on steering wheel, mind elsewhere","Hands only","Slow push","Dusk","Match cut","hands resting on a car steering wheel at a red light at dusk, city blurred beyond"),
        S("15-20s","Feet in grass, present","Feet close","Static","Bright sun","Cut to frame 1","bare feet standing in green grass in bright sun, sharp detail")],
 sound="Muffled, underwater-like ambience that snaps into clarity on 'be there'.",
 title="Your Mind Wanders Almost Half the Time You're Awake",
 desc="Across thousands of phone check-ins, minds wandered 46.9% of the time - and people were less happy when they did. Your Mind, Measured #7. Source: Science (2010).",
 tags=["mindfulness","happiness","psychology"],
 comment="Where was your mind right before this video?",
 cta="#8: you missed a day of your habit. Here's what the research says it cost you.",
 loop="The sharp, present shot cuts back to the blurred daydream - the viewer notices the contrast on replay.",
 length="~20s", exp="Sound-design reveal (muffled to clear) as the payoff", metric="Average view duration"),

dict(day=4, n=8, cat="Habits", hooktype="Relief statement answering a fear",
 topic="Missing one day doesn't break a habit",
 claim="Lally et al. (2010) followed 96 people forming a new daily habit for 12 weeks: reaching automaticity took a median of 66 days (range 18-254), and missing one opportunity did not materially affect the process.",
 sources=[("Lally et al. 2010, European Journal of Social Psychology 40(6)","https://doi.org/10.1002/ejsp.674")],
 frame="A habit-tracker grid on paper, one empty square in a long line of ticks. Text: YOU MISSED A DAY.",
 hook="You missed a day. Your habit is fine.",
 script=[("0.0-1.5","You missed a day. Your habit is fine."),
         ("1.5-5.0","In a University College London study, 96 people built a new daily habit for 12 weeks."),
         ("5.0-15.0","On average it took 66 days before it felt automatic. Some took 18. Some took over 200. And missing a single day didn't meaningfully set anyone back."),
         ("15.0-20.0","The streak was never the habit. Tomorrow is.")],
 osd=[("0.0-1.5","YOU MISSED\nA DAY"),("1.5-5.0","96 people, 12 weeks"),("5.0-10.0","~66 days to automatic"),("10.0-15.0","1 missed day = fine"),("15.0-20.0","tomorrow is")],
 shots=[S("0-1.5s","Tracker with one gap","Top-down paper","Slow push to the gap","Soft desk light","Hard cut","a hand-drawn habit tracker grid on paper with a long row of checkmarks and one empty square, top-down"),
        S("1.5-5s","Morning routine","Hands making tea","Static","Morning light","Crossfade","hands pouring tea at a kitchen counter in soft morning light"),
        S("5-15s","Pages of a calendar turning","Calendar close","Timelapse","Warm","Match cut","calendar pages turning quickly through weeks, warm light"),
        S("15-20s","Pen ticking the next box","Hand and pen","Static","Soft","Cut to frame 1","a hand ticking the next square on a habit tracker with a pen")],
 sound="A pencil tick on every tick mark; one missing tick (silence) on the gap, then the rhythm resumes.",
 title="Missing One Day Doesn't Break a Habit, a 12-Week Study Found",
 desc="In a UCL study, new habits took a median of 66 days - and missing a single day didn't set people back. Your Mind, Measured #8. Source: Lally et al. (2010).",
 tags=["habits","discipline","motivation"],
 comment="What habit are you building - and what day are you on?",
 cta="#9: how long it really takes to get back to work after one interruption.",
 loop="The next tick lands back on the tracker from frame 1.",
 length="~19s", exp="Answers a common fear; tests 'relief' against 'shock' (#5)", metric="Subscribers per 1,000 views"),

dict(day=5, n=9, cat="Focus", hooktype="Cost of something the viewer just did",
 topic="The time cost of an interruption",
 claim="Gloria Mark's field studies at UC Irvine found that when office workers were interrupted, it took an average of about 23 minutes to return to the original task, typically after working on two other tasks in between; interrupted people worked faster but reported more stress.",
 sources=[("Mark, Gudith & Klocke 2008, 'The Cost of Interrupted Work', CHI '08","https://doi.org/10.1145/1357054.1357072"),
          ("Fast Company interview with Gloria Mark (23 min 15 s figure)","https://www.fastcompany.com/944128/worker-interrupted-cost-task-switching")],
 note="The 23-minute figure is time to get back to the interrupted task, not to 'regain full focus'. The script keeps that wording.",
 frame="A phone face-up on a desk lighting up with a stack of notifications, a half-finished document blurred behind it. Text: -23 MINUTES.",
 hook="One interruption can cost you 23 minutes.",
 script=[("0.0-1.5","One interruption can cost you 23 minutes."),
         ("1.5-5.0","Researchers at UC Irvine followed office workers through their real days."),
         ("5.0-15.0","When someone got pulled off a task, it took an average of 23 minutes to get back to it, usually after two other things in between. Interrupted people worked faster, but felt more stressed."),
         ("15.0-20.0","Phone face down. Just for the next hour. Try it.")],
 osd=[("0.0-1.5","-23 MINUTES"),("1.5-5.0","real office workers"),("5.0-11.0","23 min to get back"),("11.0-15.0","faster, more stressed"),("15.0-20.0","phone face down")],
 shots=[S("0-1.5s","Phone lighting up","Phone foreground, doc blurred","Static","Screen glow","Hard cut","a phone lying face-up on a desk lighting up with a stack of notifications, a half-finished document blurred on a monitor behind"),
        S("1.5-5s","Open-plan office","Wide, backs of people","Slow dolly","Fluorescent","Crossfade","a busy open-plan office seen from behind the desks, people at screens, fluorescent light"),
        S("5-15s","Clock + many tabs","Monitor full of tabs","Slow push","Cool","Match cut","a monitor crowded with open browser tabs and a wall clock blurred behind it"),
        S("15-20s","Phone turned face down","Hand flipping phone","Static","Warm, calm","Cut to frame 1","a hand turning a phone face down on a clean wooden desk, calm warm light")],
 sound="Notification pings stacking up to a clutter, then total quiet when the phone flips over.",
 title="After an Interruption, It Took 23 Minutes to Get Back on Task",
 desc="Office workers took about 23 minutes on average to return to an interrupted task. Your Mind, Measured #9. Source: Gloria Mark, UC Irvine.",
 tags=["focus","productivity","deepwork"],
 comment="How many notifications did you get while watching this?",
 cta="#10: why losing $100 hurts about twice as much as finding $100.",
 loop="The face-down phone lights up again on replay - the interruption loop, literally.",
 length="~20s", exp="Ping sound effects on frame 1 (sound-on hook) - does audio lift 'stayed'?", metric="Viewed vs swiped"),

dict(day=5, n=10, cat="Decisions / money", hooktype="Money comparison",
 topic="Loss aversion",
 claim="Kahneman & Tversky's research on loss aversion found losses weigh roughly twice as much as equal gains (Tversky & Kahneman 1992 estimated a loss-aversion coefficient of about 2.25). Most people refuse a 50/50 bet to lose $100 or win $100.",
 sources=[("Kahneman & Tversky 1979, Econometrica 47(2) - Prospect Theory","https://doi.org/10.2307/1914185"),
          ("Tversky & Kahneman 1992, J. Risk and Uncertainty 5","https://doi.org/10.1007/BF00122574")],
 note="'About twice' is the classic estimate; some recent studies find a smaller effect for small stakes. Keep 'about'.",
 frame="A $100 bill caught mid-air falling toward a storm drain on a wet street. Text: THIS HURTS 2x.",
 hook="Losing $100 hurts about twice as much as finding $100 feels good.",
 script=[("0.0-2.0","Losing $100 hurts about twice as much as finding $100 feels good."),
         ("2.0-5.0","Kahneman and Tversky called it loss aversion."),
         ("5.0-15.0","Offer a coin flip, lose 100 or win 100, and most people say no. Many need the win near 200. It's why you stay in things you've outgrown."),
         ("15.0-21.0","Scared to quit? Ask: is it bad, or just a loss?")],
 osd=[("0.0-2.0","LOSS = 2x"),("2.0-5.0","loss aversion"),("5.0-10.0","coin flip: +100 / -100?"),("10.0-15.0","most say no"),("15.0-21.0","bad - or just a loss?")],
 shots=[S("0-2s","Bill falling to a drain","Bill mid-air","Slow motion","Wet street reflections","Hard cut","a US one hundred dollar bill falling in slow motion toward a storm drain on a wet city street, reflections of neon"),
        S("2-5s","Coin spinning","Coin close on table","Slow motion","Hard side light","Crossfade","a coin spinning on a dark table in slow motion, hard side light"),
        S("5-15s","Hand hesitating over a door","Hand on a door handle","Static","Dim hallway","Match cut","a hand hesitating on a door handle in a dim hallway, light leaking under the door"),
        S("15-21s","Door opening to light","From behind","Push through","Bright daylight","Cut to frame 1","a person seen from behind opening a door onto bright open daylight")],
 sound="Paper flutter, then a hollow 'drop' as the bill falls. Coin spin whirr. Door creak into open air.",
 title="Losing $100 Hurts About Twice as Much as Finding $100",
 desc="Losses weigh roughly twice as much as equal gains - loss aversion, measured by Kahneman and Tversky. Your Mind, Measured #10.",
 tags=["psychology","money","decisions"],
 comment="What did you stay in too long because leaving felt like losing?",
 cta="#11: people chose MORE pain in an experiment. The reason explains your memories.",
 loop="The bright doorway cuts back to the falling bill.",
 length="~21s", exp="Money hook (US audience) vs abstract hooks", metric="Shares per 1,000 views"),

dict(day=6, n=11, cat="Memory", hooktype="Paradox",
 topic="The peak-end rule",
 claim="Kahneman et al. (1993): participants held a hand in 14 C water for 60 seconds, and in another trial for 60 seconds plus 30 more as it warmed slightly; most chose to repeat the longer trial. Redelmeier, Katz & Kahneman (2003) randomized 682 colonoscopy patients; a gentler added ending made the whole procedure remembered as less unpleasant.",
 sources=[("Kahneman, Fredrickson, Schreiber & Redelmeier 1993, Psychological Science 4(6)","https://doi.org/10.1111/j.1467-9280.1993.tb00589.x"),
          ("Redelmeier, Katz & Kahneman 2003, Pain 104","https://pubmed.ncbi.nlm.nih.gov/12927615/")],
 frame="A hand plunged into a bowl of icy water, frost on the bowl's rim. Text: THEY CHOSE MORE PAIN.",
 hook="People chose more pain, because it ended better.",
 script=[("0.0-1.5","People chose more pain, because it ended better."),
         ("1.5-5.0","Cold water, 60 seconds. Then 90 seconds, the last 30 slightly warmer."),
         ("5.0-15.0","Asked which to repeat, most chose the longer one. Memory doesn't add up minutes; it keeps the worst moment and the last. Doctors saw it in 682 colonoscopy patients."),
         ("15.0-20.0","So end today on something good. It's the part you'll remember.")],
 osd=[("0.0-1.5","THEY CHOSE\nMORE PAIN"),("1.5-5.0","60s vs 60s + 30s"),("5.0-10.0","most chose longer"),("10.0-15.0","worst moment + ending"),("15.0-20.0","end on something good")],
 shots=[S("0-1.5s","Hand in ice water","Hand + bowl close","Static","Cold blue","Hard cut","a hand plunged into a glass bowl of icy water with floating ice cubes, frost on the rim, cold blue light"),
        S("1.5-5s","Stopwatch","Close","Static","Clinical","Crossfade","a stopwatch counting seconds beside a bowl of ice water, clinical light"),
        S("5-15s","Memory as film strip","Film strip with two frames lit","Slow pan","Warm projector light","Match cut","a strip of old film where only two frames are brightly lit, projector light"),
        S("15-20s","Warm evening scene","Hands around mug, sunset","Static","Golden hour","Cut to frame 1","two hands wrapped around a warm mug on a balcony at sunset")],
 sound="Cold, glassy tones at the start that warm into a soft chord at the end - the peak-end rule in audio.",
 title="People Chose the Longer Pain Because It Ended Better",
 desc="Most people chose to repeat 90 seconds of cold water over 60 because the last 30 were gentler. Your Mind, Measured #11. Sources: Kahneman et al. (1993); Redelmeier et al. (2003).",
 tags=["psychology","memory","mindset"],
 comment="What's the best last five minutes of your day?",
 cta="#12: even your worst-case deadline is probably too optimistic. There's a study.",
 loop="Warm hands cut back to the cold hands - same framing, opposite temperature.",
 length="~20s", exp="Paradox hook ('chose more pain')", metric="Viewed vs swiped"),

dict(day=6, n=12, cat="Productivity", hooktype="Challenge to the viewer's estimate",
 topic="The planning fallacy",
 claim="Buehler, Griffin & Ross (1994): students predicted finishing their thesis in 33.9 days on average; it took 55.5 days. Their 'worst case' estimate averaged 48.6 days - still too short.",
 sources=[("Buehler, Griffin & Ross 1994, J. Personality & Social Psychology 67(3)","https://doi.org/10.1037/0022-3514.67.3.366")],
 frame="A desk calendar with a deadline circled in red and three more red circles scrawled after it. Text: YOUR WORST CASE IS WRONG.",
 hook="Even your worst-case guess is probably too optimistic.",
 script=[("0.0-1.8","Even your worst-case guess is probably too optimistic."),
         ("1.8-5.0","Psychologists asked students when they'd finish their thesis."),
         ("5.0-15.0","Average guess: 34 days. If everything went wrong: 49. Actual: 55 and a half. Their worst case wasn't bad enough. It's called the planning fallacy. You picture the plan, not the interruptions."),
         ("15.0-20.0","So take your honest guess, then plan past your worst one.")],
 osd=[("0.0-1.8","WORST CASE\n= TOO SHORT"),("1.8-5.0","thesis deadlines"),("5.0-9.0","guess: 34 days"),("9.0-12.0","worst case: 49"),("12.0-15.0","actual: 55.5"),("15.0-20.0","plan past it")],
 shots=[S("0-1.8s","Calendar with extra circles","Calendar close","Slow push","Desk lamp","Hard cut","a desk calendar with one date circled in red and several more red circles scribbled on later dates, desk lamp light"),
        S("1.8-5s","Stack of papers","Top-down","Static","Soft","Crossfade","a tall stack of thesis papers and sticky notes on a desk, top-down"),
        S("5-15s","Hourglass","Hourglass centered","Timelapse","Warm backlight","Match cut","an hourglass with sand running out, warm backlight, dark background"),
        S("15-20s","Plan with buffer","Hand writing","Static","Morning light","Cut to frame 1","a hand writing a schedule with extra space blocked out in a planner, morning light")],
 sound="Tick-tock rising in speed through the numbers; a subtle deflating note on 'wasn't bad enough'.",
 title="Students' Worst-Case Deadline Guesses Were Still Too Short",
 desc="Students guessed 34 days, said 49 in the worst case - and took 55.5. The planning fallacy. Your Mind, Measured #12. Source: Buehler et al., JPSP (1994).",
 tags=["productivity","planning","psychology"],
 comment="What took you WAY longer than you planned?",
 cta="#13: what scrolling does to your mood - and it's not the time it takes.",
 loop="The planner returns to the calendar, same red ink.",
 length="~20s", exp="Three numbers on screen in sequence (data-reveal pacing)", metric="Average percentage viewed"),

dict(day=7, n=13, cat="Social media / mood", hooktype="Reframes a daily habit",
 topic="Passive scrolling lowers mood through envy",
 claim="Verduyn et al. (2015): passive Facebook use (browsing without interacting) predicted declines in affective well-being over time, explained by increased envy; active use did not.",
 sources=[("Verduyn et al. 2015, J. Experimental Psychology: General 144(2)","https://pubmed.ncbi.nlm.nih.gov/25706656/")],
 frame="A thumb mid-scroll on a phone full of glossy vacation photos in a dark room. Text: IT'S NOT THE TIME.",
 hook="Scrolling isn't what lowers your mood. Comparing is.",
 script=[("0.0-1.8","Scrolling isn't what lowers your mood. Comparing is."),
         ("1.8-5.0","Researchers texted people five times a day to ask how they felt."),
         ("5.0-15.0","The more they scrolled without posting or talking to anyone, the worse they felt later. The reason wasn't time. It was envy: their normal day against everyone's best one."),
         ("15.0-20.0","So don't just watch. Comment on this. Talk to someone.")],
 osd=[("0.0-1.8","IT'S NOT\nTHE TIME"),("1.8-5.0","5 check-ins a day"),("5.0-10.0","passive scrolling"),("10.0-15.0","= envy"),("15.0-20.0","don't just watch")],
 shots=[S("0-1.8s","Thumb scrolling glossy feed","Phone close, no face","Static","Phone glow in dark","Hard cut","a thumb scrolling a phone screen full of glossy beach vacation photos in a dark room, phone glow"),
        S("1.8-5s","Phone check-in buzz","Phone on bed","Static","Night","Crossfade","a phone buzzing on a bed sheet at night, screen glow"),
        S("5-15s","Perfect photo vs ordinary kitchen","Phone held up in front of a grey room","Slow push","Contrast","Match cut","a bright perfect vacation photo on a phone held up in front of an ordinary grey kitchen"),
        S("15-20s","A message sent","Hands typing, warm","Static","Warm","Cut to frame 1","two hands typing a message on a phone in warm light, a reply bubble appearing")],
 sound="Endless scroll 'swish' loop, a slightly sour chord on 'envy', warm resolution on 'talk to someone'.",
 title="Passive Scrolling Lowered People's Mood - Envy Was Why",
 desc="Scrolling without interacting predicted a drop in mood over time, driven by envy. Your Mind, Measured #13. Source: Verduyn et al. (2015).",
 tags=["socialmedia","mentalhealth","psychology"],
 comment="Who have you been meaning to message? Tell us who - then message them.",
 cta="#14: why the things you build yourself feel worth more.",
 loop="The typed message dissolves back into the endless scroll.",
 length="~20s", exp="The script itself asks for a comment (active use is the payoff)", metric="Comments per 1,000 views"),

dict(day=7, n=14, cat="Meaning / effort", hooktype="Surprising value claim",
 topic="The IKEA effect",
 claim="Norton, Mochon & Ariely (2012): people who assembled IKEA storage boxes themselves were willing to pay about 63% more for them than for identical pre-assembled boxes; the effect disappeared when they didn't finish.",
 sources=[("Norton, Mochon & Ariely 2012, J. Consumer Psychology 22(3)","https://doi.org/10.1016/j.jcps.2011.08.002")],
 frame="Two hands tightening the last screw on a flat-pack box, an Allen key in frame. Text: YOU'D PAY 63% MORE.",
 hook="You value things more just because you built them.",
 script=[("0.0-1.5","You value things more just because you built them."),
         ("1.5-5.0","Harvard researchers gave people plain flat-pack storage boxes."),
         ("5.0-15.0","Some assembled their own. Others got them already built. The builders were willing to pay about 63 percent more for the exact same box. But only if they finished it."),
         ("15.0-20.0","That's why the life you build slowly will feel like yours. Finish it.")],
 osd=[("0.0-1.5","YOU'D PAY\n63% MORE"),("1.5-5.0","the IKEA effect"),("5.0-10.0","built vs pre-built"),("10.0-15.0","only if finished"),("15.0-20.0","finish it")],
 shots=[S("0-1.5s","Hands with Allen key","Hands + box close","Slow push","Warm lamp","Hard cut","two hands tightening the last screw on a small flat-pack wooden box with an Allen key, warm lamp light"),
        S("1.5-5s","Flat-pack parts laid out","Top-down","Static","Soft daylight","Crossfade","flat-pack furniture parts, screws and an instruction sheet laid out on a wooden floor, top-down"),
        S("5-15s","Two identical boxes","Side by side","Slow orbit","Studio","Match cut","two identical assembled storage boxes side by side on a table, one with a small handwritten label, studio light"),
        S("15-20s","Finished room at sunset","From behind, person in doorway","Slow push","Golden hour","Cut to frame 1","a person seen from behind standing in the doorway of a small room they furnished themselves at sunset")],
 sound="Tactile foley: screws, clicks, a satisfying final 'click' at 1.3s. Warm, hopeful close.",
 title="People Paid About 63% More for Boxes They Built Themselves",
 desc="People valued boxes they built themselves about 63% more than identical pre-built ones - if they finished. Your Mind, Measured #14. Source: Norton, Mochon & Ariely (2012).",
 tags=["motivation","psychology","growth"],
 comment="What's something you built that nobody could buy from you?",
 cta="That's the first 14. Week two starts right after: 14 more things your mind does that nobody told you.",
 loop="The finished room cuts back to the last screw being turned.",
 length="~20s", exp="Effort/meaning angle with a concrete number", metric="Subscribers per 1,000 views"),
]
